#!/usr/bin/env python3
"""Workbook case + golden JSON validator.

The workbook oracle pipeline covers workbook-level features that are NOT
formula results -- pivot tables and print areas. It keeps three on-disk
artefacts in sync per suite:

  * tests/oracle/cases_wb/<suite>.yaml         -- human-authored source
  * tests/oracle/cases_wb/<suite>.case.json    -- JSON mirror consumed by
                                                  the future workbook driver
  * tests/oracle/golden_wb/<suite>.golden.json -- Excel-actual golden,
                                                  generated by a product-
                                                  verified Windows + Excel
                                                  host (absent while pending)

A workbook case carries a whole mini-workbook spec: `sheets` (cell data),
`column_widths` / `row_heights` (layout), and two optional feature blocks
`pivot` and `print`. A pivot may declare `page_fields` and post-build
`formula_probes` (`id`, sheet-qualified `cell`, and `formula`). This
validator checks the *case* JSON and -- when it exists -- the *golden* JSON:
structural shape, required fields, `id` uniqueness, and cross-file
consistency (every case id in the case file must appear in the golden, and
vice versa). The golden may legitimately be absent while external M365
capture is pending; in that case the case file is validated on its own.

Usage:
    python3 tools/oracle/workbook_case_schema.py \\
        tests/oracle/cases_wb/example_smoke.case.json \\
        [tests/oracle/golden_wb/example_smoke.golden.json]

Exits 0 on success, 1 on validation failure (with a path-and-field
location printed to stderr).
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from pathlib import Path
from typing import Any, List, Optional, Set, Tuple

# Local imports -- accept both `python3 tools/oracle/workbook_case_schema.py`
# (no package) and `python3 -m tools.oracle.workbook_case_schema`.
try:  # pragma: no cover - trivial fallback
    from tools.oracle.case_schema import _normalise_value
except ImportError:  # pragma: no cover
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from case_schema import _normalise_value  # type: ignore


# The `kind` discriminator every workbook suite must declare. Mirrors the
# `"kind": "workbook"` field the C++ runner checks on each golden file.
_SUITE_KIND = "workbook"


class ValidationError(Exception):
    """Validation failure with a path-and-field hint."""


def normalise_case_source(doc: Any) -> Any:
    """Canonicalise YAML shorthand for semantic YAML/JSON mirror checks.

    The checked-in JSON mirror uses explicit ``{kind, value}`` cell records,
    while the human YAML source intentionally permits scalars.  Normalize
    both representations before comparing the complete document so a drift
    in pivot/print/layout data cannot hide behind matching descriptions.
    """

    out = copy.deepcopy(doc)
    if not isinstance(out, dict):
        return out
    for key, value in list(out.items()):
        if key == "description" and isinstance(value, str):
            out[key] = " ".join(value.split())
    cases = out.get("cases")
    if isinstance(cases, list):
        for case_index, case in enumerate(cases):
            if not isinstance(case, dict):
                continue
            if isinstance(case.get("description"), str):
                case["description"] = " ".join(case["description"].split())
            sheets = case.get("sheets")
            if not isinstance(sheets, dict):
                continue
            for sheet_name, cells in list(sheets.items()):
                if not isinstance(cells, dict):
                    continue
                sheets[sheet_name] = {
                    address: _normalise_value(value, where=f"cases/{case_index}/sheets/{sheet_name}/{address}")
                    for address, value in cells.items()
                }
    return out


def _at(*parts: Any) -> str:
    """Renders a JSON-pointer-ish location for an error message."""
    return "/" + "/".join(str(p) for p in parts) if parts else "/"


def _require_keys(obj: Any, keys: List[str], where: str) -> None:
    if not isinstance(obj, dict):
        raise ValidationError(f"{where}: expected mapping, got {type(obj).__name__}")
    missing = [k for k in keys if k not in obj]
    if missing:
        raise ValidationError(f"{where}: missing required keys {missing}")


def _validate_sheets(sheets: Any, where: str) -> None:
    """Validates the per-case `sheets` block.

    Shape: a mapping of sheet-name -> mapping of A1-address -> cell value.
    Cell values are normalised exactly the same way `case_schema` does for
    the formula track, so the shorthand rules (bare number, leading-`=`
    formula, etc.) carry over unchanged.
    """

    if not isinstance(sheets, dict):
        raise ValidationError(f"{where}: expected mapping of sheet-name -> cells")
    for sheet_name, cells in sheets.items():
        if not isinstance(sheet_name, str) or not sheet_name:
            raise ValidationError(f"{where}: sheet name must be a non-empty string")
        if not isinstance(cells, dict):
            raise ValidationError(f"{where}/{sheet_name}: expected mapping of A1-address -> value")
        for addr, value in cells.items():
            if not isinstance(addr, str) or not addr:
                raise ValidationError(f"{where}/{sheet_name}: cell key must be a non-empty A1 address")
            # `_normalise_value` raises ValueError on a malformed record;
            # re-wrap it as a ValidationError so the CLI prints one shape.
            try:
                _normalise_value(value, where=f"{where}/{sheet_name}/{addr}")
            except ValueError as exc:
                raise ValidationError(str(exc)) from exc


def _validate_dimension_map(raw: Any, where: str, *, label: str) -> None:
    """Validates a `column_widths` / `row_heights` mapping.

    Both are optional mappings of a string key (a column letter / span or a
    row number) to a positive number. The key grammar is intentionally not
    pinned beyond "non-empty string" -- the workbook driver, not this
    validator, is the authority on what Excel accepts.
    """

    if not isinstance(raw, dict):
        raise ValidationError(f"{where}: {label} must be a mapping")
    for key, num in raw.items():
        if not isinstance(key, str) or not key:
            raise ValidationError(f"{where}: {label} key must be a non-empty string")
        if isinstance(num, bool) or not isinstance(num, (int, float)):
            raise ValidationError(f"{where}/{key}: {label} value must be a number, got {num!r}")
        if num <= 0:
            raise ValidationError(f"{where}/{key}: {label} value must be positive, got {num!r}")


def _validate_hidden_list(raw: Any, where: str, *, label: str) -> None:
    """Validates a `hidden_columns` / `hidden_rows` list.

    Hiding is deliberately its own field rather than a zero entry in the
    width / height map: a hidden column is not a zero-width one, and the
    two differ exactly where pagination cares. `_validate_dimension_map`
    rejects non-positive sizes for that reason.
    """

    if not isinstance(raw, list) or not raw:
        raise ValidationError(f"{where}: expected a non-empty list of {label}s")
    seen: Set[str] = set()
    for i, item in enumerate(raw):
        key = str(item) if isinstance(item, int) and not isinstance(item, bool) else item
        if not isinstance(key, str) or not key:
            raise ValidationError(f"{where}/{i}: expected a {label}, got {item!r}")
        if key in seen:
            raise ValidationError(f"{where}/{i}: duplicate {label} {key!r}")
        seen.add(key)


def _validate_pivot_block(raw: Any, where: str) -> None:
    """Validate the declarative pivot block and optional formula probes.

    ``formula_probes`` deliberately lives beside the pivot definition: the
    Windows driver creates the PivotTable first, then writes these formulas
    and reads their results.  This catches GETPIVOTDATA behaviour that a
    rendered-grid comparison cannot observe (notably page/data-axis field
    routing).
    """

    if not isinstance(raw, dict):
        raise ValidationError(f"{where}: pivot block must be a mapping")

    axis_values = {}
    for axis in ("row_fields", "col_fields", "page_fields"):
        if axis not in raw or raw[axis] is None:
            continue
        fields = raw[axis]
        if not isinstance(fields, list):
            raise ValidationError(f"{where}/{axis}: expected a list of field names")
        for i, field in enumerate(fields):
            if not isinstance(field, str) or not field:
                raise ValidationError(f"{where}/{axis}/{i}: expected a non-empty string")
        axis_values[axis] = fields
    seen_axis: Set[str] = set()
    for axis, fields in axis_values.items():
        overlap = seen_axis.intersection(fields)
        if overlap:
            raise ValidationError(f"{where}/{axis}: field appears on multiple axes: {sorted(overlap)}")
        seen_axis.update(fields)
    data_fields = raw.get("data_fields")
    if isinstance(data_fields, list):
        for i, data_field in enumerate(data_fields):
            if isinstance(data_field, dict) and data_field.get("field") in seen_axis:
                raise ValidationError(f"{where}/data_fields/{i}: data field overlaps a row/column/page axis")

    if "formula_probes" not in raw or raw["formula_probes"] is None:
        return
    probes = raw["formula_probes"]
    if not isinstance(probes, list) or not probes:
        raise ValidationError(f"{where}/formula_probes: expected a non-empty list")
    seen: Set[str] = set()
    for i, probe in enumerate(probes):
        probe_where = _at(where, "formula_probes", i)
        if not isinstance(probe, dict):
            raise ValidationError(f"{probe_where}: expected a mapping")
        for key in ("id", "cell", "formula"):
            if key not in probe or not isinstance(probe[key], str) or not probe[key]:
                raise ValidationError(f"{probe_where}/{key}: expected a non-empty string")
        if not probe["formula"].startswith("="):
            raise ValidationError(f"{probe_where}/formula: expected an Excel formula beginning with '='")
        if not re.fullmatch(r"(?:'[^']+'|[A-Za-z_][^!]*)![A-Za-z]{1,3}[1-9][0-9]*", probe["cell"]):
            raise ValidationError(f"{probe_where}/cell: expected a valid sheet-qualified A1 address (Sheet!A1)")
        if probe["id"] in seen:
            raise ValidationError(f"{probe_where}/id: duplicate formula probe id {probe['id']!r}")
        seen.add(probe["id"])


# Page orientations the `print.page_setup` block accepts.
_PRINT_ORIENTATIONS = {"portrait", "landscape", "default"}


# Field name -> accepted Python type for every `roundtrip` sub-block.
# Unlike the `print` block these mirror the print-authoring API's own
# parameters one-for-one, because a roundtrip case's job is to state
# exactly what a caller would call and nothing else.
_ROUNDTRIP_PAGE_SETUP_FIELDS = {
    "orientation": int,
    "paper_size": int,
    "scale": int,
    "fit_to_width": int,
    "fit_to_height": int,
    "fit_to_page": bool,
}
_ROUNDTRIP_MARGIN_FIELDS = ("left", "right", "top", "bottom", "header", "footer")
_ROUNDTRIP_PRINT_OPTION_FIELDS = ("grid_lines", "headings", "horizontal_centered", "vertical_centered")
_ROUNDTRIP_HEADER_FOOTER_TEXT = (
    "odd_header",
    "odd_footer",
    "even_header",
    "even_footer",
    "first_header",
    "first_footer",
)
_ROUNDTRIP_HEADER_FOOTER_FLAGS = (
    "different_odd_even",
    "different_first",
    "scale_with_doc",
    "align_with_margins",
)
_ROUNDTRIP_BLOCK_KEYS = frozenset(
    {
        "sheet",
        "page_setup",
        "page_margins",
        "print_options",
        "header_footer",
        "print_area",
        "print_titles",
        "row_breaks",
        "col_breaks",
    }
)

# Column letters, as `col_breaks` and `print_titles` spell them.
_COLUMN_LETTERS_RE = re.compile(r"^[A-Za-z]{1,3}$")


def _validate_roundtrip_block(raw: Any, where: str) -> None:
    """Validates a `roundtrip` feature block.

    The block states the print settings Formulon should author before the
    workbook is written and handed to Excel. Every member is optional
    except `sheet`, and each one maps to a single print-authoring call.

    Unknown keys are rejected rather than ignored. A misspelled sub-block
    would author nothing, and the capture would then record Excel
    resolving the file's defaults -- a golden that looks like a clean pass
    while testing nothing the case describes.
    """

    if not isinstance(raw, dict):
        raise ValidationError(f"{where}: roundtrip block must be a mapping")

    unknown = sorted(set(raw) - _ROUNDTRIP_BLOCK_KEYS)
    if unknown:
        raise ValidationError(
            f"{where}: unknown roundtrip field(s) {unknown}; expected {sorted(_ROUNDTRIP_BLOCK_KEYS)}"
        )

    if "sheet" not in raw:
        raise ValidationError(f"{where}: roundtrip block missing required 'sheet'")
    if not isinstance(raw["sheet"], str) or not raw["sheet"]:
        raise ValidationError(f"{where}/sheet: expected non-empty string")

    setup = raw.get("page_setup")
    if setup is not None:
        if not isinstance(setup, dict):
            raise ValidationError(f"{where}/page_setup: expected mapping")
        unknown = sorted(set(setup) - set(_ROUNDTRIP_PAGE_SETUP_FIELDS))
        if unknown:
            raise ValidationError(f"{where}/page_setup: unknown field(s) {unknown}")
        for field, expected in _ROUNDTRIP_PAGE_SETUP_FIELDS.items():
            if field not in setup or setup[field] is None:
                continue
            value = setup[field]
            if expected is bool:
                if not isinstance(value, bool):
                    raise ValidationError(f"{where}/page_setup/{field}: expected a boolean, got {value!r}")
            elif isinstance(value, bool) or not isinstance(value, int):
                raise ValidationError(f"{where}/page_setup/{field}: expected an integer, got {value!r}")

    margins = raw.get("page_margins")
    if margins is not None:
        if not isinstance(margins, dict):
            raise ValidationError(f"{where}/page_margins: expected mapping")
        unknown = sorted(set(margins) - set(_ROUNDTRIP_MARGIN_FIELDS))
        if unknown:
            raise ValidationError(f"{where}/page_margins: unknown field(s) {unknown}")
        for field in _ROUNDTRIP_MARGIN_FIELDS:
            if field not in margins or margins[field] is None:
                continue
            value = margins[field]
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ValidationError(f"{where}/page_margins/{field}: expected a number, got {value!r}")
            if value < 0:
                raise ValidationError(f"{where}/page_margins/{field}: must be non-negative, got {value!r}")

    options = raw.get("print_options")
    if options is not None:
        if not isinstance(options, dict):
            raise ValidationError(f"{where}/print_options: expected mapping")
        unknown = sorted(set(options) - set(_ROUNDTRIP_PRINT_OPTION_FIELDS))
        if unknown:
            raise ValidationError(f"{where}/print_options: unknown field(s) {unknown}")
        for field in _ROUNDTRIP_PRINT_OPTION_FIELDS:
            if field in options and options[field] is not None and not isinstance(options[field], bool):
                raise ValidationError(f"{where}/print_options/{field}: expected a boolean, got {options[field]!r}")

    header_footer = raw.get("header_footer")
    if header_footer is not None:
        if not isinstance(header_footer, dict):
            raise ValidationError(f"{where}/header_footer: expected mapping")
        allowed = set(_ROUNDTRIP_HEADER_FOOTER_TEXT) | set(_ROUNDTRIP_HEADER_FOOTER_FLAGS)
        unknown = sorted(set(header_footer) - allowed)
        if unknown:
            raise ValidationError(f"{where}/header_footer: unknown field(s) {unknown}")
        for field in _ROUNDTRIP_HEADER_FOOTER_TEXT:
            # An empty string is meaningful here -- it clears the section --
            # so only the type is checked.
            if field in header_footer and header_footer[field] is not None:
                if not isinstance(header_footer[field], str):
                    raise ValidationError(f"{where}/header_footer/{field}: expected a string")
        for field in _ROUNDTRIP_HEADER_FOOTER_FLAGS:
            if field in header_footer and header_footer[field] is not None:
                if not isinstance(header_footer[field], bool):
                    raise ValidationError(f"{where}/header_footer/{field}: expected a boolean")

    if raw.get("print_area") is not None:
        if not isinstance(raw["print_area"], str) or not raw["print_area"]:
            raise ValidationError(f"{where}/print_area: expected non-empty string")

    titles = raw.get("print_titles")
    if titles is not None:
        if not isinstance(titles, dict):
            raise ValidationError(f"{where}/print_titles: expected mapping")
        unknown = sorted(set(titles) - {"repeat_rows", "repeat_cols"})
        if unknown:
            raise ValidationError(f"{where}/print_titles: unknown field(s) {unknown}")
        for axis in ("repeat_rows", "repeat_cols"):
            if axis in titles and titles[axis] is not None:
                if not isinstance(titles[axis], str) or not titles[axis]:
                    raise ValidationError(f"{where}/print_titles/{axis}: expected non-empty string")

    rows = raw.get("row_breaks")
    if rows is not None:
        if not isinstance(rows, list):
            raise ValidationError(f"{where}/row_breaks: expected a list")
        for i, row in enumerate(rows):
            if isinstance(row, bool) or not isinstance(row, int) or row < 1:
                raise ValidationError(f"{where}/row_breaks[{i}]: expected a 1-based row number, got {row!r}")

    cols = raw.get("col_breaks")
    if cols is not None:
        if not isinstance(cols, list):
            raise ValidationError(f"{where}/col_breaks: expected a list")
        for i, col in enumerate(cols):
            if not isinstance(col, str) or not _COLUMN_LETTERS_RE.match(col):
                raise ValidationError(f"{where}/col_breaks[{i}]: expected column letters, got {col!r}")


def _validate_print_block(raw: Any, where: str) -> None:
    """Validates a `print` feature block.

    Shape (see `tests/oracle/workbook_builder.h` for the authoritative
    reference):

      * `sheet`         -- REQUIRED non-empty string: the sheet to
                           paginate.
      * `print_area`    -- optional string: an A1 range, possibly
                           comma-separated multi-area.
      * `print_titles`  -- optional mapping with optional string `rows`
                           / `cols` members.
      * `page_setup`    -- optional mapping; `orientation` is one of
                           portrait / landscape / default, the remaining
                           fields (`paper`, `scale`, `fit_to_width`,
                           `fit_to_height`) are non-negative numbers.
      * `manual_breaks` -- optional mapping with optional `rows` (list of
                           1-based row numbers) / `cols` (list of column
                           letters).
    """

    if not isinstance(raw, dict):
        raise ValidationError(f"{where}: print block must be a mapping")

    if "sheet" not in raw:
        raise ValidationError(f"{where}: print block missing required 'sheet'")
    if not isinstance(raw["sheet"], str) or not raw["sheet"]:
        raise ValidationError(f"{where}/sheet: expected non-empty string")

    if "print_area" in raw and raw["print_area"] is not None:
        if not isinstance(raw["print_area"], str) or not raw["print_area"]:
            raise ValidationError(f"{where}/print_area: expected non-empty string")

    if "print_titles" in raw and raw["print_titles"] is not None:
        titles = raw["print_titles"]
        if not isinstance(titles, dict):
            raise ValidationError(f"{where}/print_titles: expected mapping")
        for axis in ("rows", "cols"):
            if axis in titles and titles[axis] is not None:
                if not isinstance(titles[axis], str) or not titles[axis]:
                    raise ValidationError(f"{where}/print_titles/{axis}: expected non-empty string")

    if "page_setup" in raw and raw["page_setup"] is not None:
        setup = raw["page_setup"]
        if not isinstance(setup, dict):
            raise ValidationError(f"{where}/page_setup: expected mapping")
        if "orientation" in setup and setup["orientation"] is not None:
            if setup["orientation"] not in _PRINT_ORIENTATIONS:
                raise ValidationError(
                    f"{where}/page_setup/orientation: expected one of "
                    f"{sorted(_PRINT_ORIENTATIONS)}, got {setup['orientation']!r}"
                )
        for field in ("paper", "scale", "fit_to_width", "fit_to_height"):
            if field in setup and setup[field] is not None:
                num = setup[field]
                if isinstance(num, bool) or not isinstance(num, (int, float)):
                    raise ValidationError(f"{where}/page_setup/{field}: expected a number, got {num!r}")
                if num < 0:
                    raise ValidationError(f"{where}/page_setup/{field}: must be non-negative, got {num!r}")

    if "manual_breaks" in raw and raw["manual_breaks"] is not None:
        breaks = raw["manual_breaks"]
        if not isinstance(breaks, dict):
            raise ValidationError(f"{where}/manual_breaks: expected mapping")
        if "rows" in breaks and breaks["rows"] is not None:
            rows = breaks["rows"]
            if not isinstance(rows, list):
                raise ValidationError(f"{where}/manual_breaks/rows: expected a list")
            for i, row in enumerate(rows):
                if isinstance(row, bool) or not isinstance(row, (int, float)):
                    raise ValidationError(f"{where}/manual_breaks/rows/{i}: expected a 1-based row number, got {row!r}")
                if row < 1:
                    raise ValidationError(f"{where}/manual_breaks/rows/{i}: row number must be >= 1, got {row!r}")
        if "cols" in breaks and breaks["cols"] is not None:
            cols = breaks["cols"]
            if not isinstance(cols, list):
                raise ValidationError(f"{where}/manual_breaks/cols: expected a list")
            for i, col in enumerate(cols):
                if not isinstance(col, str) or not col:
                    raise ValidationError(f"{where}/manual_breaks/cols/{i}: expected a column letter, got {col!r}")


def _validate_case_entry(case: Any, where: str) -> str:
    """Validates one workbook case and returns its id."""

    _require_keys(case, ["id", "sheets"], where)
    cid = case["id"]
    if not isinstance(cid, str) or not cid:
        raise ValidationError(f"{where}/id: expected non-empty string")
    if "description" in case and not isinstance(case["description"], str):
        raise ValidationError(f"{where}/description: expected string")

    _validate_sheets(case["sheets"], f"{where}/sheets")

    if "column_widths" in case and case["column_widths"] is not None:
        _validate_dimension_map(case["column_widths"], f"{where}/column_widths", label="column_widths")
    if "row_heights" in case and case["row_heights"] is not None:
        _validate_dimension_map(case["row_heights"], f"{where}/row_heights", label="row_heights")
    if "hidden_columns" in case and case["hidden_columns"] is not None:
        _validate_hidden_list(case["hidden_columns"], f"{where}/hidden_columns", label="column letter")
    if "hidden_rows" in case and case["hidden_rows"] is not None:
        _validate_hidden_list(case["hidden_rows"], f"{where}/hidden_rows", label="1-based row number")
    if "pivot" in case and case["pivot"] is not None:
        _validate_pivot_block(case["pivot"], f"{where}/pivot")
    if "print" in case and case["print"] is not None:
        _validate_print_block(case["print"], f"{where}/print")
    if "roundtrip" in case and case["roundtrip"] is not None:
        _validate_roundtrip_block(case["roundtrip"], f"{where}/roundtrip")

    return cid


def validate_case_json(doc: Any) -> List[str]:
    """Validates a workbook case file; returns the declared case ids."""

    _require_keys(doc, ["suite", "kind", "cases"], _at())
    if not isinstance(doc["suite"], str) or not doc["suite"]:
        raise ValidationError(f"{_at('suite')}: expected non-empty string")
    if doc["kind"] != _SUITE_KIND:
        raise ValidationError(f"{_at('kind')}: expected {_SUITE_KIND!r}, got {doc['kind']!r}")
    if "description" in doc and not isinstance(doc["description"], str):
        raise ValidationError(f"{_at('description')}: expected string")
    cases = doc["cases"]
    if not isinstance(cases, list) or not cases:
        raise ValidationError(f"{_at('cases')}: expected non-empty list")

    ids: List[str] = []
    seen: Set[str] = set()
    for i, case in enumerate(cases):
        cid = _validate_case_entry(case, _at("cases", i))
        if cid in seen:
            raise ValidationError(f"{_at('cases', i, 'id')}: duplicate id {cid!r}")
        seen.add(cid)
        ids.append(cid)
    return ids


# Every sub-block a `roundtrip` capture must report, and the fields
# inside it. The capture reads all of them unconditionally -- a field the
# host could not answer is recorded as null rather than omitted -- so a
# missing key means the golden was produced by an older capture and is
# not comparable against the current one.
_ROUNDTRIP_EXPECT_SHAPE = {
    "page_setup": ("paper_size", "orientation", "zoom", "fit_to_pages_wide", "fit_to_pages_tall"),
    "page_margins": _ROUNDTRIP_MARGIN_FIELDS,
    "print_options": _ROUNDTRIP_PRINT_OPTION_FIELDS,
}
_ROUNDTRIP_EXPECT_SCALARS = ("print_area", "print_title_rows", "print_title_cols")
_ROUNDTRIP_EXPECT_LISTS = ("manual_row_breaks", "manual_col_breaks")


def _validate_roundtrip_expect(expect: Any, where: str) -> None:
    """Validates the `roundtrip` block of a golden's `expect`.

    A round-trip golden is the only artefact that says Excel read what we
    wrote, so an incomplete one is worse than none: a sub-block that
    silently went missing reads as "nothing to compare" on the C++ side.
    """

    if not isinstance(expect, dict):
        raise ValidationError(f"{where}: expected mapping")
    observed = expect.get("roundtrip")
    if not isinstance(observed, dict):
        raise ValidationError(f"{where}/roundtrip: a roundtrip case must report a roundtrip block")

    for block, fields in _ROUNDTRIP_EXPECT_SHAPE.items():
        sub = observed.get(block)
        if not isinstance(sub, dict):
            raise ValidationError(f"{where}/roundtrip/{block}: expected mapping")
        missing = [f for f in fields if f not in sub]
        if missing:
            raise ValidationError(f"{where}/roundtrip/{block}: missing field(s) {missing}")

    header_footer = observed.get("header_footer")
    if not isinstance(header_footer, dict):
        raise ValidationError(f"{where}/roundtrip/header_footer: expected mapping")

    for field in _ROUNDTRIP_EXPECT_SCALARS:
        if field not in observed:
            raise ValidationError(f"{where}/roundtrip/{field}: missing")
        if not isinstance(observed[field], str):
            raise ValidationError(f"{where}/roundtrip/{field}: expected string")

    for field in _ROUNDTRIP_EXPECT_LISTS:
        value = observed.get(field)
        if not isinstance(value, list):
            raise ValidationError(f"{where}/roundtrip/{field}: expected a list")
        for i, item in enumerate(value):
            if isinstance(item, bool) or not isinstance(item, int) or item < 0:
                raise ValidationError(f"{where}/roundtrip/{field}[{i}]: expected a zero-based index, got {item!r}")

    # The digest is what ties this golden to a specific authored workbook.
    # Without it a stale golden cannot be told from a current one.
    digest = observed.get("xlsx_sha256")
    if not isinstance(digest, str) or len(digest) != 64:
        raise ValidationError(f"{where}/roundtrip/xlsx_sha256: expected a sha256 hex digest")


def validate_golden_json(doc: Any) -> List[str]:
    """Validates a workbook golden file; returns the declared case ids."""

    _require_keys(doc, ["suite", "kind", "cases"], _at())
    if not isinstance(doc["suite"], str) or not doc["suite"]:
        raise ValidationError(f"{_at('suite')}: expected non-empty string")
    if doc["kind"] != _SUITE_KIND:
        raise ValidationError(f"{_at('kind')}: expected {_SUITE_KIND!r}, got {doc['kind']!r}")
    cases = doc["cases"]
    if not isinstance(cases, list) or not cases:
        raise ValidationError(f"{_at('cases')}: expected non-empty list")

    ids: List[str] = []
    seen: Set[str] = set()
    for i, case in enumerate(cases):
        where = _at("cases", i)
        # A divergence.yaml skip-oracle entry produces a case with
        # `"skipped": "<reason>"` in place of `"expect"`. Accept either
        # shape; the C++ runner / test surfaces the skip via GTEST_SKIP.
        _require_keys(case, ["id", "spec"], where)
        cid = case["id"]
        if not isinstance(cid, str) or not cid:
            raise ValidationError(f"{where}/id: expected non-empty string")
        if cid in seen:
            raise ValidationError(f"{where}/id: duplicate id {cid!r}")
        seen.add(cid)
        if not isinstance(case["spec"], dict):
            raise ValidationError(f"{where}/spec: expected mapping")
        has_expect = "expect" in case
        has_skipped = "skipped" in case
        if not has_expect and not has_skipped:
            raise ValidationError(f"{where}: missing required key 'expect' or 'skipped'")
        if has_expect and not isinstance(case["expect"], dict):
            raise ValidationError(f"{where}/expect: expected mapping")

        # `observed` is what Excel answered for a case the verifier still
        # skips -- evidence for adjudicating a pending divergence, never an
        # assertion. Pin that distinction here so it cannot quietly become a
        # second source of truth: it is only meaningful next to `skipped`,
        # and a case that carries `expect` has nothing to adjudicate.
        for advisory in ("observed", "observed_error"):
            if advisory not in case:
                continue
            if not has_skipped:
                raise ValidationError(f"{where}/{advisory}: only valid on a skipped case")
            if has_expect:
                raise ValidationError(f"{where}/{advisory}: a case with 'expect' is not pending adjudication")
        if "observed" in case and not isinstance(case["observed"], dict):
            raise ValidationError(f"{where}/observed: expected mapping")
        if "observed_error" in case and not isinstance(case["observed_error"], str):
            raise ValidationError(f"{where}/observed_error: expected string")
        if "observed" in case and "observed_error" in case:
            raise ValidationError(f"{where}: 'observed' and 'observed_error' are mutually exclusive")
        if has_expect:
            spec_pivot = case["spec"].get("pivot") if isinstance(case["spec"], dict) else None
            if isinstance(spec_pivot, dict) and spec_pivot.get("formula_probes") is not None:
                expected_probes = case["expect"].get("formula_probes")
                if not isinstance(expected_probes, list):
                    raise ValidationError(f"{where}/expect/formula_probes: expected a list")
                expected_ids: Set[str] = set()
                for j, result in enumerate(expected_probes):
                    result_where = _at(where, "expect", "formula_probes", j)
                    if not isinstance(result, dict):
                        raise ValidationError(f"{result_where}: expected a mapping")
                    if not isinstance(result.get("id"), str) or not result["id"]:
                        raise ValidationError(f"{result_where}/id: expected a non-empty string")
                    if result["id"] in expected_ids:
                        raise ValidationError(f"{result_where}/id: duplicate formula probe id {result['id']!r}")
                    expected_ids.add(result["id"])
                    if "result" not in result or not isinstance(result["result"], dict):
                        raise ValidationError(f"{result_where}/result: expected a result mapping")
                    kind = result["result"].get("kind")
                    if kind not in {"blank", "number", "text", "bool", "error", "array"}:
                        raise ValidationError(f"{result_where}/result/kind: unsupported result kind {kind!r}")
                    if kind == "error" and not isinstance(result["result"].get("code"), str):
                        raise ValidationError(f"{result_where}/result/code: error result needs a string code")
                    if kind != "blank" and kind != "error" and "value" not in result["result"]:
                        raise ValidationError(f"{result_where}/result/value: result kind needs a value")
                declared_ids = {p.get("id") for p in spec_pivot["formula_probes"] if isinstance(p, dict)}
                if expected_ids != declared_ids:
                    raise ValidationError(
                        f"{where}/expect/formula_probes: ids do not match declared probes "
                        f"(expected {sorted(declared_ids)}, got {sorted(expected_ids)})"
                    )
            if isinstance(case["spec"].get("roundtrip"), dict):
                _validate_roundtrip_expect(case["expect"], _at(where, "expect"))
        if has_skipped and (not isinstance(case["skipped"], str) or not case["skipped"]):
            raise ValidationError(f"{where}/skipped: expected non-empty string")
        ids.append(cid)
    return ids


def _load_json(path: Path) -> Any:
    if not path.exists():
        raise ValidationError(f"{path}: file does not exist")
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def validate_pair(case_path: Path, golden_path: Optional[Path]) -> Tuple[List[str], Optional[List[str]]]:
    """Validates the case file and (when present) the golden file.

    When `golden_path` is None or points at a missing file, only the case
    file is validated -- that is the expected state before the workbook
    driver has run on a Windows host. When both exist, their case-id sets
    are asserted equal.
    """

    case_doc = _load_json(case_path)
    case_ids = validate_case_json(case_doc)

    if golden_path is None or not golden_path.exists():
        return case_ids, None

    golden_doc = _load_json(golden_path)
    golden_ids = validate_golden_json(golden_doc)

    case_set = set(case_ids)
    golden_set = set(golden_ids)
    missing_in_golden = sorted(case_set - golden_set)
    missing_in_case = sorted(golden_set - case_set)
    if missing_in_golden:
        raise ValidationError(f"{golden_path}: missing case ids present in {case_path.name}: {missing_in_golden}")
    if missing_in_case:
        raise ValidationError(f"{case_path}: missing case ids present in {golden_path.name}: {missing_in_case}")
    return case_ids, golden_ids


def _build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Validate a workbook case JSON file and its golden JSON file.",
    )
    p.add_argument(
        "case_json",
        type=Path,
        help="Path to tests/oracle/cases_wb/<suite>.case.json",
    )
    p.add_argument(
        "golden_json",
        type=Path,
        nargs="?",
        default=None,
        help=(
            "Optional path to tests/oracle/golden_wb/<suite>.golden.json. "
            "When omitted or absent, only the case file is validated."
        ),
    )
    return p


def main(argv: List[str]) -> int:
    args = _build_arg_parser().parse_args(argv)
    try:
        case_ids, golden_ids = validate_pair(args.case_json, args.golden_json)
    except ValidationError as exc:
        print(f"validation error: {exc}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as exc:
        print(f"JSON parse error: {exc}", file=sys.stderr)
        return 1
    if golden_ids is None:
        print(f"OK: {args.case_json} (no golden checked) ({len(case_ids)} case(s): {', '.join(case_ids)})")
    else:
        print(f"OK: {args.case_json} <-> {args.golden_json} ({len(case_ids)} case(s): {', '.join(case_ids)})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
