#!/usr/bin/env python3
"""Workbook case + golden JSON validator.

The workbook oracle pipeline covers workbook-level features that are NOT
formula results -- pivot tables and print areas. It keeps three on-disk
artefacts in sync per suite:

  * tests/oracle/cases_wb/<suite>.yaml         -- human-authored source
  * tests/oracle/cases_wb/<suite>.case.json    -- JSON mirror consumed by
                                                  the future workbook driver
  * tests/oracle/golden_wb/<suite>.golden.json -- Excel-actual golden,
                                                  generated by a Windows +
                                                  Excel host (absent until
                                                  the driver has been run)

A workbook case carries a whole mini-workbook spec: `sheets` (cell data),
`column_widths` / `row_heights` (layout), and two optional feature blocks
`pivot` and `print`. This validator checks the *case* JSON and -- when it
exists -- the *golden* JSON: structural shape, required fields, `id`
uniqueness, and cross-file consistency (every case id in the case file
must appear in the golden, and vice versa). The golden may legitimately
be absent (not yet generated on a Windows host); in that case the case
file is validated on its own.

Usage:
    python3 tools/oracle/workbook_case_schema.py \\
        tests/oracle/cases_wb/example_smoke.case.json \\
        [tests/oracle/golden_wb/example_smoke.golden.json]

Exits 0 on success, 1 on validation failure (with a path-and-field
location printed to stderr).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

# Local imports -- accept both `python3 tools/oracle/workbook_case_schema.py`
# (no package) and `python3 -m tools.oracle.workbook_case_schema`.
try:  # pragma: no cover - trivial fallback
    from tools.oracle.case_schema import _normalise_value
except ImportError:  # pragma: no cover
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from case_schema import _normalise_value  # type: ignore


# The `kind` discriminator every workbook suite must declare. Mirrors the
# `"kind": "workbook"` field the C++ runner checks on each golden file.
_SUITE_KIND = "workbook"


class ValidationError(Exception):
    """Validation failure with a path-and-field hint."""


def _at(*parts: Any) -> str:
    """Renders a JSON-pointer-ish location for an error message."""
    return "/" + "/".join(str(p) for p in parts) if parts else "/"


def _require_keys(obj: Any, keys: List[str], where: str) -> None:
    if not isinstance(obj, dict):
        raise ValidationError(f"{where}: expected mapping, got {type(obj).__name__}")
    missing = [k for k in keys if k not in obj]
    if missing:
        raise ValidationError(f"{where}: missing required keys {missing}")


def _validate_sheets(sheets: Any, where: str) -> None:
    """Validates the per-case `sheets` block.

    Shape: a mapping of sheet-name -> mapping of A1-address -> cell value.
    Cell values are normalised exactly the same way `case_schema` does for
    the formula track, so the shorthand rules (bare number, leading-`=`
    formula, etc.) carry over unchanged.
    """

    if not isinstance(sheets, dict):
        raise ValidationError(f"{where}: expected mapping of sheet-name -> cells")
    for sheet_name, cells in sheets.items():
        if not isinstance(sheet_name, str) or not sheet_name:
            raise ValidationError(f"{where}: sheet name must be a non-empty string")
        if not isinstance(cells, dict):
            raise ValidationError(
                f"{where}/{sheet_name}: expected mapping of A1-address -> value"
            )
        for addr, value in cells.items():
            if not isinstance(addr, str) or not addr:
                raise ValidationError(
                    f"{where}/{sheet_name}: cell key must be a non-empty A1 address"
                )
            # `_normalise_value` raises ValueError on a malformed record;
            # re-wrap it as a ValidationError so the CLI prints one shape.
            try:
                _normalise_value(value, where=f"{where}/{sheet_name}/{addr}")
            except ValueError as exc:
                raise ValidationError(str(exc)) from exc


def _validate_dimension_map(raw: Any, where: str, *, label: str) -> None:
    """Validates a `column_widths` / `row_heights` mapping.

    Both are optional mappings of a string key (a column letter / span or a
    row number) to a positive number. The key grammar is intentionally not
    pinned beyond "non-empty string" -- the workbook driver, not this
    validator, is the authority on what Excel accepts.
    """

    if not isinstance(raw, dict):
        raise ValidationError(f"{where}: {label} must be a mapping")
    for key, num in raw.items():
        if not isinstance(key, str) or not key:
            raise ValidationError(f"{where}: {label} key must be a non-empty string")
        if isinstance(num, bool) or not isinstance(num, (int, float)):
            raise ValidationError(
                f"{where}/{key}: {label} value must be a number, got {num!r}"
            )
        if num <= 0:
            raise ValidationError(
                f"{where}/{key}: {label} value must be positive, got {num!r}"
            )


def _validate_pivot_block(raw: Any, where: str) -> None:
    """Validates a `pivot` feature block.

    The pivot block is still validated as an opaque mapping: the pivot
    builder (`tests/oracle/workbook_builder.cpp`) is the authority on its
    field shape, and the existing pivot suites already exercise it end
    to end. Only the container type is asserted here.
    """

    if not isinstance(raw, dict):
        raise ValidationError(f"{where}: pivot block must be a mapping")


# Page orientations the `print.page_setup` block accepts.
_PRINT_ORIENTATIONS = {"portrait", "landscape", "default"}


def _validate_print_block(raw: Any, where: str) -> None:
    """Validates a `print` feature block.

    Shape (see `tests/oracle/workbook_builder.h` for the authoritative
    reference):

      * `sheet`         -- REQUIRED non-empty string: the sheet to
                           paginate.
      * `print_area`    -- optional string: an A1 range, possibly
                           comma-separated multi-area.
      * `print_titles`  -- optional mapping with optional string `rows`
                           / `cols` members.
      * `page_setup`    -- optional mapping; `orientation` is one of
                           portrait / landscape / default, the remaining
                           fields (`paper`, `scale`, `fit_to_width`,
                           `fit_to_height`) are non-negative numbers.
      * `manual_breaks` -- optional mapping with optional `rows` (list of
                           1-based row numbers) / `cols` (list of column
                           letters).
    """

    if not isinstance(raw, dict):
        raise ValidationError(f"{where}: print block must be a mapping")

    if "sheet" not in raw:
        raise ValidationError(f"{where}: print block missing required 'sheet'")
    if not isinstance(raw["sheet"], str) or not raw["sheet"]:
        raise ValidationError(f"{where}/sheet: expected non-empty string")

    if "print_area" in raw and raw["print_area"] is not None:
        if not isinstance(raw["print_area"], str) or not raw["print_area"]:
            raise ValidationError(f"{where}/print_area: expected non-empty string")

    if "print_titles" in raw and raw["print_titles"] is not None:
        titles = raw["print_titles"]
        if not isinstance(titles, dict):
            raise ValidationError(f"{where}/print_titles: expected mapping")
        for axis in ("rows", "cols"):
            if axis in titles and titles[axis] is not None:
                if not isinstance(titles[axis], str) or not titles[axis]:
                    raise ValidationError(
                        f"{where}/print_titles/{axis}: expected non-empty string"
                    )

    if "page_setup" in raw and raw["page_setup"] is not None:
        setup = raw["page_setup"]
        if not isinstance(setup, dict):
            raise ValidationError(f"{where}/page_setup: expected mapping")
        if "orientation" in setup and setup["orientation"] is not None:
            if setup["orientation"] not in _PRINT_ORIENTATIONS:
                raise ValidationError(
                    f"{where}/page_setup/orientation: expected one of "
                    f"{sorted(_PRINT_ORIENTATIONS)}, got {setup['orientation']!r}"
                )
        for field in ("paper", "scale", "fit_to_width", "fit_to_height"):
            if field in setup and setup[field] is not None:
                num = setup[field]
                if isinstance(num, bool) or not isinstance(num, (int, float)):
                    raise ValidationError(
                        f"{where}/page_setup/{field}: expected a number, got {num!r}"
                    )
                if num < 0:
                    raise ValidationError(
                        f"{where}/page_setup/{field}: must be non-negative, got {num!r}"
                    )

    if "manual_breaks" in raw and raw["manual_breaks"] is not None:
        breaks = raw["manual_breaks"]
        if not isinstance(breaks, dict):
            raise ValidationError(f"{where}/manual_breaks: expected mapping")
        if "rows" in breaks and breaks["rows"] is not None:
            rows = breaks["rows"]
            if not isinstance(rows, list):
                raise ValidationError(f"{where}/manual_breaks/rows: expected a list")
            for i, row in enumerate(rows):
                if isinstance(row, bool) or not isinstance(row, (int, float)):
                    raise ValidationError(
                        f"{where}/manual_breaks/rows/{i}: expected a 1-based row "
                        f"number, got {row!r}"
                    )
                if row < 1:
                    raise ValidationError(
                        f"{where}/manual_breaks/rows/{i}: row number must be >= 1, "
                        f"got {row!r}"
                    )
        if "cols" in breaks and breaks["cols"] is not None:
            cols = breaks["cols"]
            if not isinstance(cols, list):
                raise ValidationError(f"{where}/manual_breaks/cols: expected a list")
            for i, col in enumerate(cols):
                if not isinstance(col, str) or not col:
                    raise ValidationError(
                        f"{where}/manual_breaks/cols/{i}: expected a column letter, "
                        f"got {col!r}"
                    )


def _validate_case_entry(case: Any, where: str) -> str:
    """Validates one workbook case and returns its id."""

    _require_keys(case, ["id", "sheets"], where)
    cid = case["id"]
    if not isinstance(cid, str) or not cid:
        raise ValidationError(f"{where}/id: expected non-empty string")
    if "description" in case and not isinstance(case["description"], str):
        raise ValidationError(f"{where}/description: expected string")

    _validate_sheets(case["sheets"], f"{where}/sheets")

    if "column_widths" in case and case["column_widths"] is not None:
        _validate_dimension_map(
            case["column_widths"], f"{where}/column_widths", label="column_widths"
        )
    if "row_heights" in case and case["row_heights"] is not None:
        _validate_dimension_map(
            case["row_heights"], f"{where}/row_heights", label="row_heights"
        )
    if "pivot" in case and case["pivot"] is not None:
        _validate_pivot_block(case["pivot"], f"{where}/pivot")
    if "print" in case and case["print"] is not None:
        _validate_print_block(case["print"], f"{where}/print")

    return cid


def validate_case_json(doc: Any) -> List[str]:
    """Validates a workbook case file; returns the declared case ids."""

    _require_keys(doc, ["suite", "kind", "cases"], _at())
    if not isinstance(doc["suite"], str) or not doc["suite"]:
        raise ValidationError(f"{_at('suite')}: expected non-empty string")
    if doc["kind"] != _SUITE_KIND:
        raise ValidationError(
            f"{_at('kind')}: expected {_SUITE_KIND!r}, got {doc['kind']!r}"
        )
    if "description" in doc and not isinstance(doc["description"], str):
        raise ValidationError(f"{_at('description')}: expected string")
    cases = doc["cases"]
    if not isinstance(cases, list) or not cases:
        raise ValidationError(f"{_at('cases')}: expected non-empty list")

    ids: List[str] = []
    seen: Set[str] = set()
    for i, case in enumerate(cases):
        cid = _validate_case_entry(case, _at("cases", i))
        if cid in seen:
            raise ValidationError(f"{_at('cases', i, 'id')}: duplicate id {cid!r}")
        seen.add(cid)
        ids.append(cid)
    return ids


def validate_golden_json(doc: Any) -> List[str]:
    """Validates a workbook golden file; returns the declared case ids."""

    _require_keys(doc, ["suite", "kind", "cases"], _at())
    if not isinstance(doc["suite"], str) or not doc["suite"]:
        raise ValidationError(f"{_at('suite')}: expected non-empty string")
    if doc["kind"] != _SUITE_KIND:
        raise ValidationError(
            f"{_at('kind')}: expected {_SUITE_KIND!r}, got {doc['kind']!r}"
        )
    cases = doc["cases"]
    if not isinstance(cases, list) or not cases:
        raise ValidationError(f"{_at('cases')}: expected non-empty list")

    ids: List[str] = []
    seen: Set[str] = set()
    for i, case in enumerate(cases):
        where = _at("cases", i)
        _require_keys(case, ["id", "spec", "expect"], where)
        cid = case["id"]
        if not isinstance(cid, str) or not cid:
            raise ValidationError(f"{where}/id: expected non-empty string")
        if cid in seen:
            raise ValidationError(f"{where}/id: duplicate id {cid!r}")
        seen.add(cid)
        if not isinstance(case["spec"], dict):
            raise ValidationError(f"{where}/spec: expected mapping")
        if not isinstance(case["expect"], dict):
            raise ValidationError(f"{where}/expect: expected mapping")
        ids.append(cid)
    return ids


def _load_json(path: Path) -> Any:
    if not path.exists():
        raise ValidationError(f"{path}: file does not exist")
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def validate_pair(
    case_path: Path, golden_path: Optional[Path]
) -> Tuple[List[str], Optional[List[str]]]:
    """Validates the case file and (when present) the golden file.

    When `golden_path` is None or points at a missing file, only the case
    file is validated -- that is the expected state before the workbook
    driver has run on a Windows host. When both exist, their case-id sets
    are asserted equal.
    """

    case_doc = _load_json(case_path)
    case_ids = validate_case_json(case_doc)

    if golden_path is None or not golden_path.exists():
        return case_ids, None

    golden_doc = _load_json(golden_path)
    golden_ids = validate_golden_json(golden_doc)

    case_set = set(case_ids)
    golden_set = set(golden_ids)
    missing_in_golden = sorted(case_set - golden_set)
    missing_in_case = sorted(golden_set - case_set)
    if missing_in_golden:
        raise ValidationError(
            f"{golden_path}: missing case ids present in {case_path.name}: "
            f"{missing_in_golden}"
        )
    if missing_in_case:
        raise ValidationError(
            f"{case_path}: missing case ids present in {golden_path.name}: "
            f"{missing_in_case}"
        )
    return case_ids, golden_ids


def _build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Validate a workbook case JSON file and its golden JSON file.",
    )
    p.add_argument(
        "case_json",
        type=Path,
        help="Path to tests/oracle/cases_wb/<suite>.case.json",
    )
    p.add_argument(
        "golden_json",
        type=Path,
        nargs="?",
        default=None,
        help=(
            "Optional path to tests/oracle/golden_wb/<suite>.golden.json. "
            "When omitted or absent, only the case file is validated."
        ),
    )
    return p


def main(argv: List[str]) -> int:
    args = _build_arg_parser().parse_args(argv)
    try:
        case_ids, golden_ids = validate_pair(args.case_json, args.golden_json)
    except ValidationError as exc:
        print(f"validation error: {exc}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as exc:
        print(f"JSON parse error: {exc}", file=sys.stderr)
        return 1
    if golden_ids is None:
        print(
            f"OK: {args.case_json} (no golden checked) "
            f"({len(case_ids)} case(s): {', '.join(case_ids)})"
        )
    else:
        print(
            f"OK: {args.case_json} <-> {args.golden_json} "
            f"({len(case_ids)} case(s): {', '.join(case_ids)})"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
