// Copyright 2026 libraz. Licensed under the MIT License.
//
// Conditional-formatting (CF) oracle smoke test. Pins Formulon's CF
// evaluator output for a small set of hand-authored scenarios so
// behaviour changes to `src/cf/cf_evaluator.cpp` surface as a CI
// failure instead of as a silent rendering regression.
//
// This binary is *paired* with the on-disk artefacts under
//   tests/oracle/cases_cf/<suite>.yaml
//   tests/oracle/cases_cf/<suite>.case.json
//   tests/oracle/golden_cf/<suite>.golden.json
// but does NOT read them: the cases are hardcoded as gtest fixtures
// here so the test binary needs neither YAML nor JSON. The Python
// validator (`tools/oracle/cf_case_schema.py`) keeps the on-disk pair
// in shape; if you change the YAML or the JSON, mirror the change in
// this file. The Excel-actual goldens under `golden_cf/` are
// regenerated by `tools/oracle/cf_oracle_gen.py` (macOS only).
//
// See `tests/oracle/cases_cf/README.md` for the schema and the
// macOS capture roadmap.

#include <cstdint>
#include <vector>

#include "cell.h"
#include "cf/cf_evaluator.h"
#include "cf/cf_match.h"
#include "cf/cf_types.h"
#include "eval/eval_context.h"
#include "eval/function_registry.h"
#include "gtest/gtest.h"
#include "sheet.h"
#include "utils/arena.h"
#include "value.h"

namespace formulon::cf {
namespace {

// Tolerances mirror tests/oracle/cases_cf/README.md so the comparison
// rules don't drift from author intent. Bumping these requires a
// matching README update.
constexpr int kColorChannelTolerance = 2;

// Reusable harness that bundles the sheet, arena, and evaluation
// context the CFHost needs. Mirrors the unit-test harness in
// tests/unit/cf/cf_evaluator_test.cpp; lifted here so the oracle
// binary stays free of test-helper headers from the unit suite.
struct CFOracleHarness {
  Sheet sheet{"Sheet1"};
  Arena arena;
  eval::EvalContext eval_ctx{sheet};

  CFHost MakeHost() {
    CFHost host;
    host.arena = &arena;
    host.registry = &eval::default_registry();
    host.eval_ctx = &eval_ctx;
    return host;
  }
};

CFCellRange MakeRange(std::uint32_t r1, std::uint32_t c1, std::uint32_t r2, std::uint32_t c2) {
  CFCellRange range{};
  range.first.row = r1;
  range.first.col = c1;
  range.last.row = r2;
  range.last.col = c2;
  return range;
}

// True when each channel of `actual` is within `kColorChannelTolerance`
// of `expected`. Used for ColorScale and DataBar fill comparisons.
testing::AssertionResult ColorMatches(const Color& expected, const Color& actual) {
  const int dr = static_cast<int>(actual.r) - static_cast<int>(expected.r);
  const int dg = static_cast<int>(actual.g) - static_cast<int>(expected.g);
  const int db = static_cast<int>(actual.b) - static_cast<int>(expected.b);
  const int da = static_cast<int>(actual.a) - static_cast<int>(expected.a);
  const int max_delta = kColorChannelTolerance;
  const int absdr = dr < 0 ? -dr : dr;
  const int absdg = dg < 0 ? -dg : dg;
  const int absdb = db < 0 ? -db : db;
  const int absda = da < 0 ? -da : da;
  if (absdr <= max_delta && absdg <= max_delta && absdb <= max_delta && absda <= max_delta) {
    return testing::AssertionSuccess();
  }
  return testing::AssertionFailure() << "expected RGBA{" << static_cast<int>(expected.r) << ","
                                     << static_cast<int>(expected.g) << "," << static_cast<int>(expected.b) << ","
                                     << static_cast<int>(expected.a) << "} got RGBA{" << static_cast<int>(actual.r)
                                     << "," << static_cast<int>(actual.g) << "," << static_cast<int>(actual.b) << ","
                                     << static_cast<int>(actual.a) << "} (per-channel tolerance " << max_delta << ")";
}

// ---------------------------------------------------------------------------
// Case 1: cellIs > 50 over A1:A3 = [10, 60, 90].
// Mirrors cases_cf/cf_smoke.yaml :: cellis_greater_than_50.
// Expected: A2 and A3 each yield one DifferentialFormat match with
// dxf_id=7, priority=1; A1 yields no matches and is absent from the
// (sparse) result.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, CellIsGreaterThan50) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(10.0));
  harness.sheet.set_cell_value(1, 0, Value::number(60.0));
  harness.sheet.set_cell_value(2, 0, Value::number(90.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::CellIs;
  rule.priority = 1;
  rule.dxf_id = 7u;
  rule.op = CellIsOperator::GreaterThan;
  rule.formula1 = "50";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 2u);

  // A2 (row=1).
  EXPECT_EQ(matches[0].cell.row, 1u);
  EXPECT_EQ(matches[0].cell.col, 0u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  EXPECT_EQ(matches[0].matches[0].priority, 1);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 7u);

  // A3 (row=2).
  EXPECT_EQ(matches[1].cell.row, 2u);
  EXPECT_EQ(matches[1].cell.col, 0u);
  ASSERT_EQ(matches[1].matches.size(), 1u);
  EXPECT_EQ(matches[1].matches[0].kind, CFMatchKind::DifferentialFormat);
  EXPECT_EQ(matches[1].matches[0].priority, 1);
  ASSERT_TRUE(matches[1].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[1].matches[0].dxf_id, 7u);
}

// ---------------------------------------------------------------------------
// Case 2: 3-stop colour scale Min/Percentile=50/Max with red/yellow/green
// over A1:A3 = [0, 50, 100].
// Mirrors cases_cf/cf_smoke.yaml :: colorscale_three_stop_red_yellow_green.
// Each cell sits exactly on a stop, so the resolved fill colour equals
// the stop colour (no interpolation rounding); the +/- 2 channel
// tolerance is therefore slack here, but it pins the documented
// comparator so a future Excel-actual golden can drift up to that
// margin without retuning the test.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ColorScaleThreeStop) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(0.0));
  harness.sheet.set_cell_value(1, 0, Value::number(50.0));
  harness.sheet.set_cell_value(2, 0, Value::number(100.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::ColorScale;
  rule.priority = 1;
  ColorScaleSpec spec;
  spec.thresholds.push_back({CfvoType::Min, "", true});
  spec.thresholds.push_back({CfvoType::Percentile, "50", true});
  spec.thresholds.push_back({CfvoType::Max, "", true});
  spec.colors.push_back({255, 0, 0, 255});
  spec.colors.push_back({255, 255, 0, 255});
  spec.colors.push_back({0, 255, 0, 255});
  rule.color_scale = std::move(spec);
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 3u);

  const Color expected[3] = {
      {255, 0, 0, 255},
      {255, 255, 0, 255},
      {0, 255, 0, 255},
  };
  for (std::size_t i = 0; i < 3; ++i) {
    SCOPED_TRACE(testing::Message() << "cell index " << i);
    EXPECT_EQ(matches[i].cell.row, static_cast<std::uint32_t>(i));
    EXPECT_EQ(matches[i].cell.col, 0u);
    ASSERT_EQ(matches[i].matches.size(), 1u);
    EXPECT_EQ(matches[i].matches[0].kind, CFMatchKind::ColorScale);
    EXPECT_EQ(matches[i].matches[0].priority, 1);
    ASSERT_TRUE(matches[i].matches[0].resolved_fill_color.has_value());
    EXPECT_TRUE(ColorMatches(expected[i], *matches[i].matches[0].resolved_fill_color));
  }
}

// ---------------------------------------------------------------------------
// Case 3: top-2 over A1:A5 = [1, 5, 3, 4, 2].
// Mirrors cases_cf/cf_smoke.yaml :: top10_top2_of_a1_to_a5.
// Expected: A2 (5) and A4 (4) each yield one DifferentialFormat match
// with dxf_id=11, priority=1; A1, A3, A5 yield no matches.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, Top10Top2) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(5.0));
  harness.sheet.set_cell_value(2, 0, Value::number(3.0));
  harness.sheet.set_cell_value(3, 0, Value::number(4.0));
  harness.sheet.set_cell_value(4, 0, Value::number(2.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 4, 0));
  CFRule rule;
  rule.type = RuleType::Top10;
  rule.priority = 1;
  rule.dxf_id = 11u;
  rule.rank = 2;
  rule.percent = false;
  rule.bottom = false;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 4, 0), host);

  ASSERT_EQ(matches.size(), 2u);

  EXPECT_EQ(matches[0].cell.row, 1u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 11u);

  EXPECT_EQ(matches[1].cell.row, 3u);
  ASSERT_EQ(matches[1].matches.size(), 1u);
  EXPECT_EQ(matches[1].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[1].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[1].matches[0].dxf_id, 11u);
}

// ---------------------------------------------------------------------------
// Case 4: above-average over A1:A5 = [1, 5, 3, 4, 2]. Mean = 3, so the
// strict above-average set is {5, 4} -> A2 and A4.
// Mirrors cases_cf/cf_smoke.yaml :: above_average_a1_to_a5.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, AboveAverage) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(5.0));
  harness.sheet.set_cell_value(2, 0, Value::number(3.0));
  harness.sheet.set_cell_value(3, 0, Value::number(4.0));
  harness.sheet.set_cell_value(4, 0, Value::number(2.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 4, 0));
  CFRule rule;
  rule.type = RuleType::AboveAverage;
  rule.priority = 1;
  rule.dxf_id = 12u;
  rule.above_average = true;
  rule.equal_average = false;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 4, 0), host);

  ASSERT_EQ(matches.size(), 2u);

  EXPECT_EQ(matches[0].cell.row, 1u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 12u);

  EXPECT_EQ(matches[1].cell.row, 3u);
  ASSERT_EQ(matches[1].matches.size(), 1u);
  EXPECT_EQ(matches[1].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[1].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[1].matches[0].dxf_id, 12u);
}

// ---------------------------------------------------------------------------
// Case 5: begins-with "foo" over A1:A3 = ["foobar", "barfoo", "food"].
// A1 ("foobar") and A3 ("food") both start with "foo"; A2 ("barfoo")
// does not. Mirrors cases_cf/cf_smoke.yaml :: begins_with_foo.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, BeginsWithFoo) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("foobar"));
  harness.sheet.set_cell_value(1, 0, Value::text("barfoo"));
  harness.sheet.set_cell_value(2, 0, Value::text("food"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::BeginsWith;
  rule.priority = 1;
  rule.dxf_id = 14u;
  rule.text = "foo";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 2u);

  EXPECT_EQ(matches[0].cell.row, 0u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 14u);

  EXPECT_EQ(matches[1].cell.row, 2u);
  ASSERT_EQ(matches[1].matches.size(), 1u);
  EXPECT_EQ(matches[1].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[1].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[1].matches[0].dxf_id, 14u);
}

// ---------------------------------------------------------------------------
// Case 6: ends-with "bar" over A1:A3 = ["foobar", "fooba", "barfoo"].
// Only A1 ("foobar") ends with "bar". Mirrors cases_cf/cf_smoke.yaml ::
// ends_with_bar.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, EndsWithBar) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("foobar"));
  harness.sheet.set_cell_value(1, 0, Value::text("fooba"));
  harness.sheet.set_cell_value(2, 0, Value::text("barfoo"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::EndsWith;
  rule.priority = 1;
  rule.dxf_id = 15u;
  rule.text = "bar";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 1u);

  EXPECT_EQ(matches[0].cell.row, 0u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 15u);
}

// ---------------------------------------------------------------------------
// Case 7: not-contains "qux" over A1:A3 = ["abc", "quxy", "def"].
// A1 and A3 (no "qux") match; A2 ("quxy") does not. Mirrors
// cases_cf/cf_smoke.yaml :: not_contains_qux.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, NotContainsQux) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("abc"));
  harness.sheet.set_cell_value(1, 0, Value::text("quxy"));
  harness.sheet.set_cell_value(2, 0, Value::text("def"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::NotContainsText;
  rule.priority = 1;
  rule.dxf_id = 16u;
  rule.text = "qux";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 2u);

  EXPECT_EQ(matches[0].cell.row, 0u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 16u);

  EXPECT_EQ(matches[1].cell.row, 2u);
  ASSERT_EQ(matches[1].matches.size(), 1u);
  EXPECT_EQ(matches[1].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[1].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[1].matches[0].dxf_id, 16u);
}

// ---------------------------------------------------------------------------
// Case 8: contains-blanks over A1:A3 = ["x", blank, "y"]. Only A2
// (truly empty) matches. Mirrors cases_cf/cf_smoke.yaml ::
// contains_blanks_a2.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ContainsBlanks) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("x"));
  // A2 is blank — leave it unset.
  harness.sheet.set_cell_value(2, 0, Value::text("y"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::ContainsBlanks;
  rule.priority = 1;
  rule.dxf_id = 17u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 1u);
  EXPECT_EQ(matches[0].cell.row, 1u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 17u);
}

// ---------------------------------------------------------------------------
// Case 9: not-contains-blanks over A1:A3 = ["x", blank, "y"]. A1 and
// A3 (non-blank) match. Mirrors cases_cf/cf_smoke.yaml ::
// not_contains_blanks_a1_a3.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, NotContainsBlanks) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("x"));
  harness.sheet.set_cell_value(2, 0, Value::text("y"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::NotContainsBlanks;
  rule.priority = 1;
  rule.dxf_id = 18u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 2u);
  EXPECT_EQ(matches[0].cell.row, 0u);
  EXPECT_EQ(matches[1].cell.row, 2u);
  for (const auto& cell : matches) {
    ASSERT_EQ(cell.matches.size(), 1u);
    EXPECT_EQ(cell.matches[0].kind, CFMatchKind::DifferentialFormat);
    ASSERT_TRUE(cell.matches[0].dxf_id.has_value());
    EXPECT_EQ(*cell.matches[0].dxf_id, 18u);
  }
}

// ---------------------------------------------------------------------------
// Case 10: contains-errors over A1:A3 where A2 = #DIV/0!. Only A2
// matches. Mirrors cases_cf/cf_smoke.yaml :: contains_errors_a2.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ContainsErrors) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("x"));
  harness.sheet.set_cell_value(1, 0, Value::error(ErrorCode::Div0));
  harness.sheet.set_cell_value(2, 0, Value::text("y"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::ContainsErrors;
  rule.priority = 1;
  rule.dxf_id = 19u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 1u);
  EXPECT_EQ(matches[0].cell.row, 1u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 19u);
}

// ---------------------------------------------------------------------------
// Case 11: not-contains-errors over A1:A3 where A2 = #DIV/0!. A1 and
// A3 (non-error) match. Mirrors cases_cf/cf_smoke.yaml ::
// not_contains_errors_a1_a3.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, NotContainsErrors) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("x"));
  harness.sheet.set_cell_value(1, 0, Value::error(ErrorCode::Div0));
  harness.sheet.set_cell_value(2, 0, Value::text("y"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::NotContainsErrors;
  rule.priority = 1;
  rule.dxf_id = 20u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 2u);
  EXPECT_EQ(matches[0].cell.row, 0u);
  EXPECT_EQ(matches[1].cell.row, 2u);
  for (const auto& cell : matches) {
    ASSERT_EQ(cell.matches.size(), 1u);
    EXPECT_EQ(cell.matches[0].kind, CFMatchKind::DifferentialFormat);
    ASSERT_TRUE(cell.matches[0].dxf_id.has_value());
    EXPECT_EQ(*cell.matches[0].dxf_id, 20u);
  }
}

// ---------------------------------------------------------------------------
// Case 12: duplicate-values over A1:A3 = [1, 2, 1]. A1 and A3 match.
// Mirrors cases_cf/cf_smoke.yaml :: duplicate_values_a1_a3.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, DuplicateValues) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(2.0));
  harness.sheet.set_cell_value(2, 0, Value::number(1.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::DuplicateValues;
  rule.priority = 1;
  rule.dxf_id = 21u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 2u);
  EXPECT_EQ(matches[0].cell.row, 0u);
  EXPECT_EQ(matches[1].cell.row, 2u);
  for (const auto& cell : matches) {
    ASSERT_EQ(cell.matches.size(), 1u);
    EXPECT_EQ(cell.matches[0].kind, CFMatchKind::DifferentialFormat);
    ASSERT_TRUE(cell.matches[0].dxf_id.has_value());
    EXPECT_EQ(*cell.matches[0].dxf_id, 21u);
  }
}

// ---------------------------------------------------------------------------
// Case 13: unique-values over A1:A3 = [1, 2, 1]. Only A2 (value 2) is
// unique. Mirrors cases_cf/cf_smoke.yaml :: unique_values_a2.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, UniqueValues) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(2.0));
  harness.sheet.set_cell_value(2, 0, Value::number(1.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::UniqueValues;
  rule.priority = 1;
  rule.dxf_id = 22u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 1u);
  EXPECT_EQ(matches[0].cell.row, 1u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 22u);
}

// ---------------------------------------------------------------------------
// Case 14: expression `MOD(ROW(),2)=0` over A1:A4 = [1, 2, 3, 4]. The
// formula matches even-numbered rows (1-based ROW()); A2 (row=1) and
// A4 (row=3) match. Mirrors cases_cf/cf_smoke.yaml :: expression_even_row.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ExpressionEvenRow) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(2.0));
  harness.sheet.set_cell_value(2, 0, Value::number(3.0));
  harness.sheet.set_cell_value(3, 0, Value::number(4.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 3, 0));
  CFRule rule;
  rule.type = RuleType::Expression;
  rule.priority = 1;
  rule.dxf_id = 23u;
  rule.formula1 = "MOD(ROW(),2)=0";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 3, 0), host);

  ASSERT_EQ(matches.size(), 2u);
  EXPECT_EQ(matches[0].cell.row, 1u);
  EXPECT_EQ(matches[1].cell.row, 3u);
  for (const auto& cell : matches) {
    ASSERT_EQ(cell.matches.size(), 1u);
    EXPECT_EQ(cell.matches[0].kind, CFMatchKind::DifferentialFormat);
    ASSERT_TRUE(cell.matches[0].dxf_id.has_value());
    EXPECT_EQ(*cell.matches[0].dxf_id, 23u);
  }
}

// ---------------------------------------------------------------------------
// Case 15: contains-text "foo" over A1:A3 = ["foobar", "bar", "foo"].
// "foobar" and "foo" both contain the literal "foo"; "bar" does not.
// Mirrors cases_cf/cf_smoke.yaml :: contains_text_foo.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ContainsTextFoo) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("foobar"));
  harness.sheet.set_cell_value(1, 0, Value::text("bar"));
  harness.sheet.set_cell_value(2, 0, Value::text("foo"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::ContainsText;
  rule.priority = 1;
  rule.dxf_id = 13u;
  rule.text = "foo";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  ASSERT_EQ(matches.size(), 2u);

  EXPECT_EQ(matches[0].cell.row, 0u);
  ASSERT_EQ(matches[0].matches.size(), 1u);
  EXPECT_EQ(matches[0].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[0].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[0].matches[0].dxf_id, 13u);

  EXPECT_EQ(matches[1].cell.row, 2u);
  ASSERT_EQ(matches[1].matches.size(), 1u);
  EXPECT_EQ(matches[1].matches[0].kind, CFMatchKind::DifferentialFormat);
  ASSERT_TRUE(matches[1].matches[0].dxf_id.has_value());
  EXPECT_EQ(*matches[1].matches[0].dxf_id, 13u);
}

}  // namespace
}  // namespace formulon::cf
