// Copyright 2026 libraz. Licensed under the Apache License, Version 2.0.
//
// Conditional-formatting (CF) oracle smoke test. Pins Formulon's CF
// evaluator output for a small set of hand-authored scenarios so
// behaviour changes to `src/cf/cf_evaluator.cpp` surface as a CI
// failure instead of as a silent rendering regression.
//
// The scenario *inputs* (sheet values and CF rule specs) are built
// programmatically per fixture below, but the *expected outputs* are
// read from the checked-in golden at
//   tests/oracle/golden_cf/<suite>.golden.json
// (path handed in via the FORMULON_CF_GOLDEN_DIR compile define), so
// the golden is the single source of truth for match expectations.
// The Excel-actual golden is regenerated by
// `tools/oracle/cf_oracle_gen.py` (macOS only); the paired input
// artefacts (`cases_cf/<suite>.yaml`, `cases_cf/<suite>.case.json`)
// are kept in shape by the Python validator
// (`tools/oracle/cf_case_schema.py`).
//
// See `tests/oracle/cases_cf/README.md` for the schema and the
// macOS capture roadmap.

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include "cell.h"
#include "cf/cf_evaluator.h"
#include "cf/cf_match.h"
#include "cf/cf_types.h"
#include "eval/eval_context.h"
#include "eval/function_registry.h"
#include "gtest/gtest.h"
#include "sheet.h"
#include "tests/oracle/json_reader.h"
#include "utils/arena.h"
#include "value.h"

#ifndef FORMULON_CF_GOLDEN_DIR
#define FORMULON_CF_GOLDEN_DIR ""
#endif

namespace formulon::cf {
namespace {

using ::formulon::tests::oracle::JsonValue;

// Loads and caches the CF golden document (parsed once per process). A
// missing or malformed golden is a test-rig error, not a per-case
// failure, so it surfaces via the accessor's ADD_FAILURE below rather
// than crashing every fixture.
const JsonValue& CfGolden() {
  static const JsonValue golden = [] {
    const std::string path = std::string(FORMULON_CF_GOLDEN_DIR) + "/cf_smoke.golden.json";
    auto parsed = ::formulon::tests::oracle::parse_json_file(path);
    if (!parsed.has_value()) {
      ADD_FAILURE() << "failed to load CF golden at " << path << ": " << parsed.error().message;
      return JsonValue::make_null();
    }
    return std::move(parsed).value();
  }();
  return golden;
}

// Returns the `cells` array for `case_id`, or nullptr if the case (or
// the golden document) is absent. The returned vector is owned by the
// process-lifetime static in CfGolden(), so the pointer stays valid.
const std::vector<JsonValue>* GoldenCellsFor(std::string_view case_id) {
  const JsonValue& root = CfGolden();
  if (!root.is_object()) {
    return nullptr;
  }
  const JsonValue* cases = root.find("cases");
  if (cases == nullptr || !cases->is_array()) {
    return nullptr;
  }
  for (const JsonValue& entry : cases->as_array()) {
    const JsonValue* id = entry.find("id");
    if (id != nullptr && id->is_string() && id->as_string() == case_id) {
      const JsonValue* cells = entry.find("cells");
      return (cells != nullptr && cells->is_array()) ? &cells->as_array() : nullptr;
    }
  }
  return nullptr;
}

std::optional<CFMatchKind> CFMatchKindFromString(const std::string& s) {
  if (s == "DifferentialFormat")
    return CFMatchKind::DifferentialFormat;
  if (s == "ColorScale")
    return CFMatchKind::ColorScale;
  if (s == "DataBar")
    return CFMatchKind::DataBar;
  if (s == "IconSet")
    return CFMatchKind::IconSet;
  return std::nullopt;
}

std::optional<IconSetName> IconSetNameFromString(const std::string& s) {
  static const std::map<std::string, IconSetName> kMap = {
      {"Three_Arrows", IconSetName::Three_Arrows},
      {"Three_ArrowsGray", IconSetName::Three_ArrowsGray},
      {"Three_Flags", IconSetName::Three_Flags},
      {"Three_TrafficLights1", IconSetName::Three_TrafficLights1},
      {"Three_TrafficLights2", IconSetName::Three_TrafficLights2},
      {"Three_Signs", IconSetName::Three_Signs},
      {"Three_Symbols", IconSetName::Three_Symbols},
      {"Three_Symbols2", IconSetName::Three_Symbols2},
      {"Four_Arrows", IconSetName::Four_Arrows},
      {"Four_ArrowsGray", IconSetName::Four_ArrowsGray},
      {"Four_RedToBlack", IconSetName::Four_RedToBlack},
      {"Four_Rating", IconSetName::Four_Rating},
      {"Four_TrafficLights", IconSetName::Four_TrafficLights},
      {"Five_Arrows", IconSetName::Five_Arrows},
      {"Five_ArrowsGray", IconSetName::Five_ArrowsGray},
      {"Five_Rating", IconSetName::Five_Rating},
      {"Five_Quarters", IconSetName::Five_Quarters},
  };
  const auto it = kMap.find(s);
  if (it == kMap.end())
    return std::nullopt;
  return it->second;
}

Color ColorFromJson(const JsonValue& j) {
  Color c{};
  if (const JsonValue* r = j.find("r"); r != nullptr)
    c.r = static_cast<std::uint8_t>(r->as_number());
  if (const JsonValue* g = j.find("g"); g != nullptr)
    c.g = static_cast<std::uint8_t>(g->as_number());
  if (const JsonValue* b = j.find("b"); b != nullptr)
    c.b = static_cast<std::uint8_t>(b->as_number());
  if (const JsonValue* a = j.find("a"); a != nullptr)
    c.a = static_cast<std::uint8_t>(a->as_number());
  return c;
}

// Tolerances mirror tests/oracle/cases_cf/README.md so the comparison
// rules don't drift from author intent. Bumping these requires a
// matching README update.
constexpr int kColorChannelTolerance = 2;

// Reusable harness that bundles the sheet, arena, and evaluation
// context the CFHost needs. Mirrors the unit-test harness in
// tests/unit/cf/cf_evaluator_test.cpp; lifted here so the oracle
// binary stays free of test-helper headers from the unit suite.
struct CFOracleHarness {
  Sheet sheet{"Sheet1"};
  Arena arena;
  eval::EvalContext eval_ctx{sheet};

  CFHost MakeHost() {
    CFHost host;
    host.arena = &arena;
    host.registry = &eval::default_registry();
    host.eval_ctx = &eval_ctx;
    return host;
  }
};

CFCellRange MakeRange(std::uint32_t r1, std::uint32_t c1, std::uint32_t r2, std::uint32_t c2) {
  CFCellRange range{};
  range.first.row = r1;
  range.first.col = c1;
  range.last.row = r2;
  range.last.col = c2;
  return range;
}

// True when each channel of `actual` is within `kColorChannelTolerance`
// of `expected`. Used for ColorScale and DataBar fill comparisons.
testing::AssertionResult ColorMatches(const Color& expected, const Color& actual) {
  const int dr = static_cast<int>(actual.r) - static_cast<int>(expected.r);
  const int dg = static_cast<int>(actual.g) - static_cast<int>(expected.g);
  const int db = static_cast<int>(actual.b) - static_cast<int>(expected.b);
  const int da = static_cast<int>(actual.a) - static_cast<int>(expected.a);
  const int max_delta = kColorChannelTolerance;
  const int absdr = dr < 0 ? -dr : dr;
  const int absdg = dg < 0 ? -dg : dg;
  const int absdb = db < 0 ? -db : db;
  const int absda = da < 0 ? -da : da;
  if (absdr <= max_delta && absdg <= max_delta && absdb <= max_delta && absda <= max_delta) {
    return testing::AssertionSuccess();
  }
  return testing::AssertionFailure() << "expected RGBA{" << static_cast<int>(expected.r) << ","
                                     << static_cast<int>(expected.g) << "," << static_cast<int>(expected.b) << ","
                                     << static_cast<int>(expected.a) << "} got RGBA{" << static_cast<int>(actual.r)
                                     << "," << static_cast<int>(actual.g) << "," << static_cast<int>(actual.b) << ","
                                     << static_cast<int>(actual.a) << "} (per-channel tolerance " << max_delta << ")";
}

// DataBar `length_pct` / `axis_position_pct` comparison tolerance, in
// percentage points. Mirrors tests/oracle/cases_cf/README.md.
constexpr double kBarLengthTolerance = 0.5;

// Compares the evaluator's sparse per-cell match list against the golden
// `cells` array for `case_id`. Kind-specific payloads are checked field
// by field; colour channels use `ColorMatches`, bar lengths use
// `kBarLengthTolerance`. This is the single expectation authority: every
// fixture builds its inputs, evaluates, then defers to this comparator.
void VerifyAgainstGolden(std::string_view case_id, const std::vector<CFRangeCellMatches>& actual) {
  const std::vector<JsonValue>* expected_cells = GoldenCellsFor(case_id);
  ASSERT_NE(expected_cells, nullptr) << "no golden cells for case '" << case_id << "'";
  ASSERT_EQ(actual.size(), expected_cells->size()) << "matched-cell count mismatch for case '" << case_id << "'";

  for (std::size_t ci = 0; ci < expected_cells->size(); ++ci) {
    SCOPED_TRACE(testing::Message() << "case '" << case_id << "' cell index " << ci);
    const JsonValue& ecell = (*expected_cells)[ci];
    const CFRangeCellMatches& acell = actual[ci];

    const JsonValue* erow = ecell.find("row");
    const JsonValue* ecol = ecell.find("col");
    ASSERT_NE(erow, nullptr);
    ASSERT_NE(ecol, nullptr);
    EXPECT_EQ(acell.cell.row, static_cast<std::uint32_t>(erow->as_number()));
    EXPECT_EQ(acell.cell.col, static_cast<std::uint32_t>(ecol->as_number()));

    const JsonValue* ematches = ecell.find("matches");
    ASSERT_NE(ematches, nullptr);
    ASSERT_TRUE(ematches->is_array());
    ASSERT_EQ(acell.matches.size(), ematches->as_array().size());

    for (std::size_t mi = 0; mi < acell.matches.size(); ++mi) {
      SCOPED_TRACE(testing::Message() << "match index " << mi);
      const JsonValue& em = ematches->as_array()[mi];
      const CFMatch& am = acell.matches[mi];

      const JsonValue* ekind = em.find("kind");
      ASSERT_NE(ekind, nullptr);
      ASSERT_TRUE(ekind->is_string());
      const std::optional<CFMatchKind> kind = CFMatchKindFromString(ekind->as_string());
      ASSERT_TRUE(kind.has_value()) << "unknown match kind '" << ekind->as_string() << "'";
      EXPECT_EQ(am.kind, *kind);

      if (const JsonValue* eprio = em.find("priority"); eprio != nullptr) {
        EXPECT_EQ(am.priority, static_cast<std::int32_t>(eprio->as_number()));
      }

      switch (*kind) {
        case CFMatchKind::DifferentialFormat: {
          const JsonValue* edxf = em.find("dxf_id");
          ASSERT_NE(edxf, nullptr);
          ASSERT_TRUE(am.dxf_id.has_value());
          EXPECT_EQ(*am.dxf_id, static_cast<std::uint32_t>(edxf->as_number()));
          break;
        }
        case CFMatchKind::ColorScale: {
          const JsonValue* ecolor = em.find("color");
          ASSERT_NE(ecolor, nullptr);
          ASSERT_TRUE(am.resolved_fill_color.has_value());
          EXPECT_TRUE(ColorMatches(ColorFromJson(*ecolor), *am.resolved_fill_color));
          break;
        }
        case CFMatchKind::DataBar: {
          ASSERT_TRUE(am.data_bar_render.has_value());
          const DataBarRender& render = *am.data_bar_render;
          if (const JsonValue* elen = em.find("bar_length_pct"); elen != nullptr) {
            EXPECT_NEAR(render.length_pct, elen->as_number(), kBarLengthTolerance);
          }
          if (const JsonValue* eaxis = em.find("bar_axis_position_pct"); eaxis != nullptr) {
            EXPECT_NEAR(render.axis_position_pct, eaxis->as_number(), kBarLengthTolerance);
          }
          if (const JsonValue* eneg = em.find("is_negative"); eneg != nullptr) {
            EXPECT_EQ(render.is_negative, eneg->as_bool());
          }
          if (const JsonValue* efill = em.find("fill"); efill != nullptr) {
            EXPECT_TRUE(ColorMatches(ColorFromJson(*efill), render.fill));
          }
          break;
        }
        case CFMatchKind::IconSet: {
          ASSERT_TRUE(am.icon_render.has_value());
          const IconRender& render = *am.icon_render;
          if (const JsonValue* ename = em.find("icon_set_name"); ename != nullptr) {
            ASSERT_TRUE(ename->is_string());
            const std::optional<IconSetName> set = IconSetNameFromString(ename->as_string());
            ASSERT_TRUE(set.has_value()) << "unknown icon set '" << ename->as_string() << "'";
            EXPECT_EQ(render.set_name, *set);
          }
          if (const JsonValue* eidx = em.find("icon_index"); eidx != nullptr) {
            EXPECT_EQ(render.icon_index, static_cast<std::uint8_t>(eidx->as_number()));
          }
          break;
        }
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Case 1: cellIs > 50 over A1:A3 = [10, 60, 90].
// Mirrors cases_cf/cf_smoke.yaml :: cellis_greater_than_50.
// Expected: A2 and A3 each yield one DifferentialFormat match with
// dxf_id=7, priority=1; A1 yields no matches and is absent from the
// (sparse) result.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, CellIsGreaterThan50) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(10.0));
  harness.sheet.set_cell_value(1, 0, Value::number(60.0));
  harness.sheet.set_cell_value(2, 0, Value::number(90.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::CellIs;
  rule.priority = 1;
  rule.dxf_id = 7u;
  rule.op = CellIsOperator::GreaterThan;
  rule.formula1 = "50";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("cellis_greater_than_50", matches);
}

// ---------------------------------------------------------------------------
// Case 2: 3-stop colour scale Min/Percentile=50/Max with red/yellow/green
// over A1:A3 = [0, 50, 100].
// Mirrors cases_cf/cf_smoke.yaml :: colorscale_three_stop_red_yellow_green.
// Each cell sits exactly on a stop, so the resolved fill colour equals
// the stop colour (no interpolation rounding); the +/- 2 channel
// tolerance is therefore slack here, but it pins the documented
// comparator so a future Excel-actual golden can drift up to that
// margin without retuning the test.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ColorScaleThreeStop) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(0.0));
  harness.sheet.set_cell_value(1, 0, Value::number(50.0));
  harness.sheet.set_cell_value(2, 0, Value::number(100.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::ColorScale;
  rule.priority = 1;
  ColorScaleSpec spec;
  spec.thresholds.push_back({CfvoType::Min, "", true});
  spec.thresholds.push_back({CfvoType::Percentile, "50", true});
  spec.thresholds.push_back({CfvoType::Max, "", true});
  spec.colors.push_back({255, 0, 0, 255});
  spec.colors.push_back({255, 255, 0, 255});
  spec.colors.push_back({0, 255, 0, 255});
  rule.color_scale = std::move(spec);
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("colorscale_three_stop_red_yellow_green", matches);
}

// ---------------------------------------------------------------------------
// Case 3: top-2 over A1:A5 = [1, 5, 3, 4, 2].
// Mirrors cases_cf/cf_smoke.yaml :: top10_top2_of_a1_to_a5.
// Expected: A2 (5) and A4 (4) each yield one DifferentialFormat match
// with dxf_id=11, priority=1; A1, A3, A5 yield no matches.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, Top10Top2) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(5.0));
  harness.sheet.set_cell_value(2, 0, Value::number(3.0));
  harness.sheet.set_cell_value(3, 0, Value::number(4.0));
  harness.sheet.set_cell_value(4, 0, Value::number(2.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 4, 0));
  CFRule rule;
  rule.type = RuleType::Top10;
  rule.priority = 1;
  rule.dxf_id = 11u;
  rule.rank = 2;
  rule.percent = false;
  rule.bottom = false;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 4, 0), host);

  VerifyAgainstGolden("top10_top2_of_a1_to_a5", matches);
}

// ---------------------------------------------------------------------------
// Case 4: above-average over A1:A5 = [1, 5, 3, 4, 2]. Mean = 3, so the
// strict above-average set is {5, 4} -> A2 and A4.
// Mirrors cases_cf/cf_smoke.yaml :: above_average_a1_to_a5.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, AboveAverage) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(5.0));
  harness.sheet.set_cell_value(2, 0, Value::number(3.0));
  harness.sheet.set_cell_value(3, 0, Value::number(4.0));
  harness.sheet.set_cell_value(4, 0, Value::number(2.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 4, 0));
  CFRule rule;
  rule.type = RuleType::AboveAverage;
  rule.priority = 1;
  rule.dxf_id = 12u;
  rule.above_average = true;
  rule.equal_average = false;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 4, 0), host);

  VerifyAgainstGolden("above_average_a1_to_a5", matches);
}

// ---------------------------------------------------------------------------
// Case 5: begins-with "foo" over A1:A3 = ["foobar", "barfoo", "food"].
// A1 ("foobar") and A3 ("food") both start with "foo"; A2 ("barfoo")
// does not. Mirrors cases_cf/cf_smoke.yaml :: begins_with_foo.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, BeginsWithFoo) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("foobar"));
  harness.sheet.set_cell_value(1, 0, Value::text("barfoo"));
  harness.sheet.set_cell_value(2, 0, Value::text("food"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::BeginsWith;
  rule.priority = 1;
  rule.dxf_id = 14u;
  rule.text = "foo";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("begins_with_foo", matches);
}

// ---------------------------------------------------------------------------
// Case 6: ends-with "bar" over A1:A3 = ["foobar", "fooba", "barfoo"].
// Only A1 ("foobar") ends with "bar". Mirrors cases_cf/cf_smoke.yaml ::
// ends_with_bar.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, EndsWithBar) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("foobar"));
  harness.sheet.set_cell_value(1, 0, Value::text("fooba"));
  harness.sheet.set_cell_value(2, 0, Value::text("barfoo"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::EndsWith;
  rule.priority = 1;
  rule.dxf_id = 15u;
  rule.text = "bar";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("ends_with_bar", matches);
}

// ---------------------------------------------------------------------------
// Case 7: not-contains "qux" over A1:A3 = ["abc", "quxy", "def"].
// A1 and A3 (no "qux") match; A2 ("quxy") does not. Mirrors
// cases_cf/cf_smoke.yaml :: not_contains_qux.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, NotContainsQux) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("abc"));
  harness.sheet.set_cell_value(1, 0, Value::text("quxy"));
  harness.sheet.set_cell_value(2, 0, Value::text("def"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::NotContainsText;
  rule.priority = 1;
  rule.dxf_id = 16u;
  rule.text = "qux";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("not_contains_qux", matches);
}

// ---------------------------------------------------------------------------
// Case 8: contains-blanks over A1:A3 = ["x", blank, "y"]. Only A2
// (truly empty) matches. Mirrors cases_cf/cf_smoke.yaml ::
// contains_blanks_a2.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ContainsBlanks) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("x"));
  // A2 is blank — leave it unset.
  harness.sheet.set_cell_value(2, 0, Value::text("y"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::ContainsBlanks;
  rule.priority = 1;
  rule.dxf_id = 17u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("contains_blanks_a2", matches);
}

// ---------------------------------------------------------------------------
// Case 9: not-contains-blanks over A1:A3 = ["x", blank, "y"]. A1 and
// A3 (non-blank) match. Mirrors cases_cf/cf_smoke.yaml ::
// not_contains_blanks_a1_a3.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, NotContainsBlanks) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("x"));
  harness.sheet.set_cell_value(2, 0, Value::text("y"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::NotContainsBlanks;
  rule.priority = 1;
  rule.dxf_id = 18u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("not_contains_blanks_a1_a3", matches);
}

// ---------------------------------------------------------------------------
// Case 10: contains-errors over A1:A3 where A2 = #DIV/0!. Only A2
// matches. Mirrors cases_cf/cf_smoke.yaml :: contains_errors_a2.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ContainsErrors) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("x"));
  harness.sheet.set_cell_value(1, 0, Value::error(ErrorCode::Div0));
  harness.sheet.set_cell_value(2, 0, Value::text("y"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::ContainsErrors;
  rule.priority = 1;
  rule.dxf_id = 19u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("contains_errors_a2", matches);
}

// ---------------------------------------------------------------------------
// Case 11: not-contains-errors over A1:A3 where A2 = #DIV/0!. A1 and
// A3 (non-error) match. Mirrors cases_cf/cf_smoke.yaml ::
// not_contains_errors_a1_a3.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, NotContainsErrors) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("x"));
  harness.sheet.set_cell_value(1, 0, Value::error(ErrorCode::Div0));
  harness.sheet.set_cell_value(2, 0, Value::text("y"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::NotContainsErrors;
  rule.priority = 1;
  rule.dxf_id = 20u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("not_contains_errors_a1_a3", matches);
}

// ---------------------------------------------------------------------------
// Case 12: duplicate-values over A1:A3 = [1, 2, 1]. A1 and A3 match.
// Mirrors cases_cf/cf_smoke.yaml :: duplicate_values_a1_a3.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, DuplicateValues) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(2.0));
  harness.sheet.set_cell_value(2, 0, Value::number(1.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::DuplicateValues;
  rule.priority = 1;
  rule.dxf_id = 21u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("duplicate_values_a1_a3", matches);
}

// ---------------------------------------------------------------------------
// Case 13: unique-values over A1:A3 = [1, 2, 1]. Only A2 (value 2) is
// unique. Mirrors cases_cf/cf_smoke.yaml :: unique_values_a2.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, UniqueValues) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(2.0));
  harness.sheet.set_cell_value(2, 0, Value::number(1.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::UniqueValues;
  rule.priority = 1;
  rule.dxf_id = 22u;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("unique_values_a2", matches);
}

// ---------------------------------------------------------------------------
// Case 14: expression `MOD(ROW(),2)=0` over A1:A4 = [1, 2, 3, 4]. The
// formula matches even-numbered rows (1-based ROW()); A2 (row=1) and
// A4 (row=3) match. Mirrors cases_cf/cf_smoke.yaml :: expression_even_row.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ExpressionEvenRow) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(1.0));
  harness.sheet.set_cell_value(1, 0, Value::number(2.0));
  harness.sheet.set_cell_value(2, 0, Value::number(3.0));
  harness.sheet.set_cell_value(3, 0, Value::number(4.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 3, 0));
  CFRule rule;
  rule.type = RuleType::Expression;
  rule.priority = 1;
  rule.dxf_id = 23u;
  rule.formula1 = "MOD(ROW(),2)=0";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 3, 0), host);

  VerifyAgainstGolden("expression_even_row", matches);
}

// ---------------------------------------------------------------------------
// Case 15: contains-text "foo" over A1:A3 = ["foobar", "bar", "foo"].
// "foobar" and "foo" both contain the literal "foo"; "bar" does not.
// Mirrors cases_cf/cf_smoke.yaml :: contains_text_foo.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, ContainsTextFoo) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::text("foobar"));
  harness.sheet.set_cell_value(1, 0, Value::text("bar"));
  harness.sheet.set_cell_value(2, 0, Value::text("foo"));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::ContainsText;
  rule.priority = 1;
  rule.dxf_id = 13u;
  rule.text = "foo";
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden("contains_text_foo", matches);
}

// ---------------------------------------------------------------------------
// Case 16: DataBar over A1:A5 = [0, 25, 50, 75, 100] with explicit
// num/0 and num/100 thresholds, blue fill, and min/max length 0/100.
// Bar length is the linear fraction `(value - min) / (max - min)`
// scaled into [0, 100], so each cell reports a bar length equal to
// its value. Mirrors cases_cf/cf_smoke.yaml :: databar_min0_max100.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, DataBarMin0Max100) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(0.0));
  harness.sheet.set_cell_value(1, 0, Value::number(25.0));
  harness.sheet.set_cell_value(2, 0, Value::number(50.0));
  harness.sheet.set_cell_value(3, 0, Value::number(75.0));
  harness.sheet.set_cell_value(4, 0, Value::number(100.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 4, 0));
  CFRule rule;
  rule.type = RuleType::DataBar;
  rule.priority = 1;
  DataBarSpec spec;
  spec.min = {CfvoType::Number, "0", true};
  spec.max = {CfvoType::Number, "100", true};
  spec.fill = {33, 150, 243, 255};
  spec.negative_fill = {255, 0, 0, 255};
  spec.min_length_pct = 0;
  spec.max_length_pct = 100;
  spec.axis_position = DataBarAxisPosition::Automatic;
  rule.data_bar = std::move(spec);
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 4, 0), host);

  VerifyAgainstGolden("databar_min0_max100", matches);
}

// ---------------------------------------------------------------------------
// Case 17: IconSet (Three_Arrows) over A1:A5 = [10, 30, 50, 70, 90]
// with Number thresholds 33 / 67 (gte=true). Bucket index per cell:
// cell < 33 -> 0; 33 <= cell < 67 -> 1; cell >= 67 -> 2. Mirrors
// cases_cf/cf_smoke.yaml :: iconset_three_arrows.
// ---------------------------------------------------------------------------

TEST(CfOracleSmoke, IconSetThreeArrows) {
  CFOracleHarness harness;
  harness.sheet.set_cell_value(0, 0, Value::number(10.0));
  harness.sheet.set_cell_value(1, 0, Value::number(30.0));
  harness.sheet.set_cell_value(2, 0, Value::number(50.0));
  harness.sheet.set_cell_value(3, 0, Value::number(70.0));
  harness.sheet.set_cell_value(4, 0, Value::number(90.0));

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 4, 0));
  CFRule rule;
  rule.type = RuleType::IconSet;
  rule.priority = 1;
  IconSetSpec spec;
  spec.name = IconSetName::Three_Arrows;
  spec.percent = false;
  spec.reverse = false;
  spec.thresholds = {
      {CfvoType::Number, "33", true},
      {CfvoType::Number, "67", true},
  };
  rule.icon_set = std::move(spec);
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 4, 0), host);

  VerifyAgainstGolden("iconset_three_arrows", matches);
}

// ---------------------------------------------------------------------------
// Cases 18-23: TimePeriod-equivalent cases. Excel's `timePeriod` rules
// read live TODAY() at evaluation time, which makes deterministic
// golden capture awkward. The smoke suite pins six day/month-bucket
// variants by rewriting each as an Expression rule that references a
// baked-in serial (today=46145 for 2026-05-03). Mirrors
// cases_cf/cf_smoke.yaml :: time_period_*_via_expression.
//
// The four week-boundary buckets (Last7Days / ThisWeek / LastWeek /
// NextWeek) need a frozen-clock capture path and are deferred.
// ---------------------------------------------------------------------------

namespace {

// Helper that builds a single-rule sheet and an Expression CF block,
// evaluates it, and defers to the golden for `case_id`. `dxf_id` still
// parameterizes the rule construction. Keeps the six TimePeriod
// fixtures small enough to read at a glance.
void RunTimePeriodExpressionCase(const double sheet_values[3], const char* formula1, std::uint32_t dxf_id,
                                 std::string_view case_id) {
  CFOracleHarness harness;
  for (std::uint32_t row = 0; row < 3; ++row) {
    harness.sheet.set_cell_value(row, 0, Value::number(sheet_values[row]));
  }

  ConditionalFormat block{};
  block.sqref.push_back(MakeRange(0, 0, 2, 0));
  CFRule rule;
  rule.type = RuleType::Expression;
  rule.priority = 1;
  rule.dxf_id = dxf_id;
  rule.formula1 = formula1;
  block.rules.push_back(std::move(rule));
  harness.sheet.mutable_conditional_formats().push_back(std::move(block));

  const CFHost host = harness.MakeHost();
  const std::vector<CFRangeCellMatches> matches = evaluate_cf_for_range(harness.sheet, MakeRange(0, 0, 2, 0), host);

  VerifyAgainstGolden(case_id, matches);
}

}  // namespace

TEST(CfOracleSmoke, TimePeriodTodayViaExpression) {
  const double values[3] = {46145.0, 46144.0, 46146.0};
  RunTimePeriodExpressionCase(values, "A1=46145", 24u, "time_period_today_via_expression");
}

TEST(CfOracleSmoke, TimePeriodYesterdayViaExpression) {
  const double values[3] = {46145.0, 46144.0, 46146.0};
  RunTimePeriodExpressionCase(values, "A1=46144", 25u, "time_period_yesterday_via_expression");
}

TEST(CfOracleSmoke, TimePeriodTomorrowViaExpression) {
  const double values[3] = {46145.0, 46144.0, 46146.0};
  RunTimePeriodExpressionCase(values, "A1=46146", 26u, "time_period_tomorrow_via_expression");
}

TEST(CfOracleSmoke, TimePeriodLastMonthViaExpression) {
  const double values[3] = {46096.0, 46127.0, 46157.0};
  RunTimePeriodExpressionCase(values, "AND(YEAR(A1)=2026,MONTH(A1)=4)", 27u, "time_period_last_month_via_expression");
}

TEST(CfOracleSmoke, TimePeriodThisMonthViaExpression) {
  const double values[3] = {46096.0, 46127.0, 46157.0};
  RunTimePeriodExpressionCase(values, "AND(YEAR(A1)=2026,MONTH(A1)=5)", 28u, "time_period_this_month_via_expression");
}

TEST(CfOracleSmoke, TimePeriodNextMonthViaExpression) {
  const double values[3] = {46127.0, 46157.0, 46188.0};
  RunTimePeriodExpressionCase(values, "AND(YEAR(A1)=2026,MONTH(A1)=6)", 29u, "time_period_next_month_via_expression");
}

}  // namespace
}  // namespace formulon::cf
