//
// Per-package emission plan for the OOXML writer. Centralises the
// numbering and collision-detection logic the writer used to derive
// across multiple passes. Built once at the top of `write_ooxml()`;
// consumed by every subsequent part builder so the file naming stays
// consistent across `[Content_Types].xml`, workbook rels, sheet rels,
// and the per-part `AddPart` calls themselves. Internal to
// `src/io/ooxml/`; not part of the public API.

#ifndef FORMULON_IO_OOXML_EMISSION_PLAN_H_
#define FORMULON_IO_OOXML_EMISSION_PLAN_H_

#include <cstdint>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

namespace formulon {

class Workbook;

namespace pivot {
class PivotCache;
class PivotTable;
}  // namespace pivot

namespace io {

struct PassthroughPart;
struct TableMetadata;
struct ExternalLinkRecord;

/// Plan we build up before any miniz call: which sheets own which
/// table parts, what filename each table uses, what passthrough parts
/// we'll emit. Centralising this here keeps `BuildContentTypes` /
/// `AddPart` calls trivial and avoids re-deriving table numbering from
/// two places.
struct EmissionPlan {
  // True when the writer generated xl/sharedStrings.xml from literal text
  // cells. This also reserves the path from passthrough collision handling.
  bool generated_shared_strings = false;
  // For each sheet (by 0-based index), the in-source TableMetadata
  // entries that target it, paired with the package-relative path the
  // writer assigned (`xl/tables/tableN.xml`). `(table_ref, path)` is
  // append-only and 1:1 with `<tablePart>` rels.
  struct PerSheetTable {
    const TableMetadata* table = nullptr;
    std::string path;
    std::uint32_t numeric_id = 0;  // matches the path's `tableN.xml` suffix
  };
  std::vector<std::vector<PerSheetTable>> tables_by_sheet;
  // Workbook-level pivot caches. One entry per `wb.pivot_caches()` in
  // document order. `numeric_id` drives the package paths; `cache_id`
  // is the workbook-level identifier consumers see (PivotTable refers
  // to it via `pivot_cache_id()`); `workbook_rid` is the rId integer
  // the workbook-rels file assigns to this cache definition.
  struct PivotCachePlan {
    const pivot::PivotCache* cache = nullptr;
    std::uint32_t numeric_id = 0;      // 1-based, package-wide
    std::string definition_path;       // "xl/pivotCache/pivotCacheDefinition1.xml"
    std::string records_path;          // "xl/pivotCache/pivotCacheRecords1.xml"
    std::string definition_rels_path;  // "xl/pivotCache/_rels/pivotCacheDefinition1.xml.rels"
    std::uint32_t workbook_rid = 0;    // workbook-rels rId number for this cache definition
    std::uint32_t cache_id = 0;        // PivotCache::cache_id(); used by <pivotCaches> entry
  };
  std::vector<PivotCachePlan> pivot_caches;
  // Pivot tables grouped by owning sheet. Each `numeric_id` is a
  // package-wide 1-based counter (independent of cache numbering); the
  // path is `xl/pivotTables/pivotTable<N>.xml`.
  struct PivotTablePlan {
    const pivot::PivotTable* table = nullptr;
    std::uint32_t numeric_id = 0;  // 1-based, package-wide
    std::string path;              // "xl/pivotTables/pivotTable1.xml"
  };
  std::vector<std::vector<PivotTablePlan>> pivot_tables_by_sheet;
  // Per-sheet comments / VML payload. `numeric_id` matches the
  // `comments<N>.xml` filename (1-based, package-wide). `vml_path` is
  // the per-sheet VML drawing path, emitted as a stub when the source
  // had none and as passthrough bytes otherwise.
  struct CommentsPlan {
    std::uint32_t numeric_id = 0;
    std::string comments_path;                    // "xl/comments<N>.xml"
    std::string vml_path;                         // "xl/drawings/vmlDrawing<N>.vml"
    const PassthroughPart* vml_source = nullptr;  // non-null => use bytes verbatim
  };
  // One entry per sheet; engaged only for sheets with at least one
  // comment. Disengaged entries have `numeric_id == 0`.
  std::vector<CommentsPlan> comments_by_sheet;
  // External link relationships. One entry per `wb.external_links()` in
  // document order. `workbook_rid` is the writer-assigned rId integer
  // for the workbook.xml.rels Relationship and the matching
  // `<externalReference r:id>` attribute in workbook.xml. The body part
  // itself rides through `passthrough_parts()`; the per-link rels file
  // (under `xl/externalLinks/_rels/`) is generated by the writer from
  // the captured target URL.
  struct ExternalLinkPlan {
    const ExternalLinkRecord* record = nullptr;
    std::uint32_t workbook_rid = 0;
  };
  std::vector<ExternalLinkPlan> external_links;
  // Passthrough parts we will keep. Entries that collide with a
  // generated path are dropped here (with a warning) so downstream
  // emission can blindly write everything in the list.
  std::vector<const PassthroughPart*> passthrough_kept;
};

/// Builds the emission plan. Performs collision detection between
/// generated and passthrough paths; collisions are logged via
/// `StructuredLog` (warn) and the passthrough copy is dropped.
EmissionPlan BuildEmissionPlan(const Workbook& wb, bool generated_shared_strings);

/// Helper: composes a path of the form `<prefix><id><suffix>` (e.g.
/// `("xl/tables/table", 3, ".xml")` -> `"xl/tables/table3.xml"`).
std::string NumberedPartPath(std::string_view prefix, std::uint32_t id, std::string_view suffix);

/// True when `plan.passthrough_kept` contains a part with the given
/// package path. Used by part builders to decide whether to emit a
/// workbook-rels relationship for a passthrough payload (theme,
/// calcChain, sharedStrings, ...).
bool HasPassthroughPart(const EmissionPlan& plan, std::string_view path);

}  // namespace io
}  // namespace formulon

#endif  // FORMULON_IO_OOXML_EMISSION_PLAN_H_
