#!/usr/bin/env python3
"""Generate Formulon's compact Unicode worksheet-name simple-fold table.

The input is Unicode's CaseFolding-17.0.0.txt. Only one-scalar C (common) and
S (simple) mappings are included; F (full/expanding) and T (Turkic) mappings
are deliberately excluded. Long arithmetic runs are emitted as `(first,
length, delta)` records and the remaining mappings as `(source, target)`
records, so the native/WASM data stays substantially smaller than a flat
code-point pair table.

The source URL, version, and SHA-256 are pinned below. Regeneration is
reproducible with:

    python3 tools/unicode/generate_casefold.py --input CaseFolding.txt \\
      > src/sheet_name_casefold_data.cpp

Use `--check` with `--input` to compare the generated bytes against the
tracked table without writing it.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

SOURCE_VERSION = "17.0.0"
SOURCE_URL = f"https://www.unicode.org/Public/{SOURCE_VERSION}/ucd/CaseFolding.txt"
SOURCE_SHA256 = "ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183"
TABLE_PATH = Path(__file__).resolve().parents[2] / "src" / "sheet_name_casefold_data.cpp"


def load_mappings(path: Path) -> dict[int, int]:
    payload = path.read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"unexpected CaseFolding source hash: {digest} (expected {SOURCE_SHA256})")

    mappings: dict[int, int] = {}
    statuses: dict[int, str] = {}
    for raw_line in payload.decode("utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [field.strip() for field in line.split(";")]
        if len(fields) == 4 and not fields[-1]:
            fields.pop()
        if len(fields) != 3:
            raise ValueError(f"malformed CaseFolding line: {raw_line!r}")
        source = int(fields[0], 16)
        status = fields[1]
        targets = [int(value, 16) for value in fields[2].split()]
        if status not in {"C", "S"} or len(targets) != 1:
            continue
        # The file emits the common mapping before its simple-only fallback;
        # retain C when both statuses occur for one source scalar.
        if source not in mappings or status == "C":
            mappings[source] = targets[0]
            statuses[source] = status

    if not mappings:
        raise ValueError("CaseFolding source produced no C/S mappings")
    return {source: target for source, target in mappings.items() if source != target}


def split_records(mappings: dict[int, int]) -> tuple[list[tuple[int, int, int]], list[tuple[int, int]]]:
    sources = sorted(mappings)
    ranges: list[tuple[int, int, int]] = []
    pairs: list[tuple[int, int]] = []
    i = 0
    while i < len(sources):
        first = sources[i]
        last = first
        while i + 1 < len(sources) and sources[i + 1] == last + 1 and mappings[sources[i + 1]] == mappings[last] + 1:
            i += 1
            last = sources[i]
        if last > first:
            ranges.append((first, last - first + 1, mappings[first] - first))
        else:
            pairs.append((first, mappings[first]))
        i += 1
    return ranges, pairs


def render(mappings: dict[int, int]) -> str:
    ranges, pairs = split_records(mappings)
    out: list[str] = [
        "//",
        "// GENERATED FILE — do not edit by hand. Regenerate via:",
        "//   python3 tools/unicode/generate_casefold.py --input CaseFolding.txt > src/sheet_name_casefold_data.cpp",
        "//",
        f"// Source: {SOURCE_URL}",
        f"// Source SHA-256: {SOURCE_SHA256}",
        "// Mappings: Unicode CaseFolding C/S only (F/T excluded).",
        f"// Records: {len(ranges)} arithmetic runs, {len(pairs)} singleton pairs.",
        "//",
        '#include "sheet_name_casefold_data.h"',
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace formulon {",
        "namespace sheet_names {",
        "namespace detail {",
        "namespace {",
        "",
        "struct CaseFoldRange {",
        "  std::uint32_t first;",
        "  std::int32_t delta;",
        "  std::uint16_t length;",
        "};",
        "",
        "struct CaseFoldPair {",
        "  std::uint32_t source;",
        "  std::uint32_t target;",
        "};",
        "",
        "// clang-format off",
        "constexpr CaseFoldRange kRanges[] = {",
    ]
    for first, length, delta in ranges:
        out.append(f"    {{0x{first:06X}u, {delta}, {length}u}},")
    out.extend(
        [
            "};",
            "",
            "constexpr CaseFoldPair kPairs[] = {",
        ]
    )
    for source, target in pairs:
        out.append(f"    {{0x{source:06X}u, 0x{target:06X}u}},")
    out.extend(
        [
            "};",
            "// clang-format on",
            "",
            "}  // namespace",
            "",
            "std::uint32_t fold_scalar(std::uint32_t scalar) noexcept {",
            "  std::size_t lo = 0;",
            f"  std::size_t hi = {len(ranges)}U;",
            "  while (lo < hi) {",
            "    const std::size_t mid = lo + (hi - lo) / 2U;",
            "    const CaseFoldRange& range = kRanges[mid];",
            "    if (scalar < range.first) {",
            "      hi = mid;",
            "      continue;",
            "    }",
            "    const std::uint32_t end = range.first + static_cast<std::uint32_t>(range.length);",
            "    if (scalar < end) {",
            "      return static_cast<std::uint32_t>(static_cast<std::int64_t>(scalar) + range.delta);",
            "    }",
            "    lo = mid + 1U;",
            "  }",
            "",
            "  lo = 0;",
            f"  hi = {len(pairs)}U;",
            "  while (lo < hi) {",
            "    const std::size_t mid = lo + (hi - lo) / 2U;",
            "    const CaseFoldPair& pair = kPairs[mid];",
            "    if (scalar < pair.source) {",
            "      hi = mid;",
            "    } else if (scalar > pair.source) {",
            "      lo = mid + 1U;",
            "    } else {",
            "      return pair.target;",
            "    }",
            "  }",
            "  return scalar;",
            "}",
            "",
            "}  // namespace detail",
            "}  // namespace sheet_names",
            "}  // namespace formulon",
            "",
        ]
    )
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--input", type=Path, required=True, help="Unicode CaseFolding-17.0.0.txt")
    parser.add_argument("--check", action="store_true", help="compare the tracked generated table")
    args = parser.parse_args(argv)
    try:
        expected = render(load_mappings(args.input)).encode("utf-8")
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"case-fold generation failed: {exc}", file=sys.stderr)
        return 2
    if args.check:
        try:
            actual = TABLE_PATH.read_bytes()
        except OSError as exc:
            print(f"cannot read {TABLE_PATH}: {exc}", file=sys.stderr)
            return 2
        if actual != expected:
            print(f"generated table drift detected: {TABLE_PATH}", file=sys.stderr)
            return 1
        return 0
    sys.stdout.buffer.write(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
