#!/usr/bin/env python3
# Copyright 2026 libraz. Licensed under the Apache License, Version 2.0.
"""Stage ``formulon_capi.wasm`` into the Python package's _wasm/ dir.

Run via ``make python-package``. Stdlib only -- no third-party deps so
this works in any clean Python 3.9+ environment.

The Python wheel is pure-Python with a bundled WebAssembly module. The
WASM is built out-of-tree by ``make wasm-capi`` (Emscripten toolchain
required); this script only copies the artefact into the package
directory so ``setup.py bdist_wheel`` can pick it up via the package-data
declaration in ``pyproject.toml``.

Inputs (defaults; override via command-line flags):
  --build-dir build-wasm-capi
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

# packages/python/scripts/stage.py -> repo root is three levels up.
REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
PKG_WASM_DIR = REPO_ROOT / "packages" / "python" / "formulon" / "_wasm"
WASM_FILENAME = "formulon_capi.wasm"


def _parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--build-dir",
        default="build-wasm-capi",
        help=(
            "Emscripten build directory containing formulon_capi.wasm "
            "(relative to repo root). Default: build-wasm-capi"
        ),
    )
    return p.parse_args(argv)


def main(argv: list[str]) -> int:
    args = _parse_args(argv)
    build_dir = (REPO_ROOT / args.build_dir).resolve()
    src = build_dir / WASM_FILENAME

    if not src.is_file():
        print(
            f"stage.py: {src} not found. Run `make wasm-capi` first.",
            file=sys.stderr,
        )
        return 1

    PKG_WASM_DIR.mkdir(parents=True, exist_ok=True)
    # Ensure the directory is a proper package (empty __init__.py keeps
    # setuptools' include-package-data discovery happy).
    init_file = PKG_WASM_DIR / "__init__.py"
    if not init_file.exists():
        init_file.write_text(
            "# Auto-generated by packages/python/scripts/stage.py.\n"
            "# This package only ships a single .wasm asset.\n"
        )

    dst = PKG_WASM_DIR / WASM_FILENAME
    shutil.copy2(src, dst)
    print(f"staged {WASM_FILENAME} -> {dst} ({dst.stat().st_size} bytes)")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
