#!/usr/bin/env python3
"""Generates the localized Excel function-name tables behind FORMULATEXT.

Input: tools/locale/data/fn_names_mac-365-<locale>.json, the name Mac Excel
shows in a formula for every catalog function (captured per UI language).
Output: src/eval/locale_function_names.{h,cpp}, holding only the names whose
spelling differs from English, as one sequence of NUL-separated records
(no offset tables; lookups scan it).

Every function in tools/catalog/functions.txt must have a captured name in
every locale, except the EXCLUDED ones Excel never shows as a name. A
function without one is a catalog gap: the run reports it and exits 2.

Usage:
    python3 tools/locale/generate_function_names.py          # rewrite the outputs
    python3 tools/locale/generate_function_names.py --check  # exit 1 on drift, 2 on a gap
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "tools" / "locale" / "data"
CATALOG_PATH = REPO_ROOT / "tools" / "catalog" / "functions.txt"
HEADER_PATH = REPO_ROOT / "src" / "eval" / "locale_function_names.h"
SOURCE_PATH = REPO_ROOT / "src" / "eval" / "locale_function_names.cpp"
REGENERATION_GUIDANCE = "Regenerate with: python3 tools/locale/generate_function_names.py"

# Data-file locale suffix -> ExcelLocale enumerator, in enum order.
LOCALES = (
    ("ja_JP", "kJaJP"),
    ("en_US", "kEnUS"),
    ("de_DE", "kDeDE"),
    ("fr_FR", "kFrFR"),
    ("zh_CN", "kZhCN"),
    ("ko_KR", "kKoKR"),
    ("th_TH", "kThTH"),
)

# Catalog functions Excel never displays by name, so no capture can exist.
EXCLUDED = {
    "_TRO_ALL": "displayed as the trim-reference operator",
    "_TRO_LEADING": "displayed as the trim-reference operator",
    "_TRO_TRAILING": "displayed as the trim-reference operator",
    "ANCHORARRAY": "displayed as the # spill operator",
    "SINGLE": "displayed as the @ operator",
    "PY": "not available in Mac Excel",
}

LINE_WIDTH = 116


def catalog() -> list[str]:
    lines = CATALOG_PATH.read_text(encoding="utf-8").splitlines()
    return [line.strip() for line in lines if line.strip() and not line.startswith("#")]


def load_names(locale: str) -> dict[str, str | None]:
    path = DATA_DIR / f"fn_names_mac-365-{locale}.json"
    return json.loads(path.read_text(encoding="utf-8"))


def catalog_gaps(names_by_locale: dict[str, dict[str, str | None]]) -> dict[str, list[str]]:
    """Returns, per locale, the catalog functions that have no captured name."""
    functions = catalog()
    gaps: dict[str, list[str]] = {}
    for locale, names in names_by_locale.items():
        missing = [fn for fn in functions if fn not in EXCLUDED and not names.get(fn)]
        if missing:
            gaps[locale] = missing
    return gaps


def localized_tables(names_by_locale: dict[str, dict[str, str | None]]) -> dict[str, list[tuple[str, str]]]:
    """Returns, per locale, the (canonical, localized) pairs that differ, sorted by canonical name."""
    tables: dict[str, list[tuple[str, str]]] = {}
    for locale, names in names_by_locale.items():
        pairs = sorted((fn, local) for fn, local in names.items() if local and local != fn and fn not in EXCLUDED)
        if pairs:
            tables[locale] = pairs
    return tables


def records(tables: dict[str, list[tuple[str, str]]]) -> bytes:
    """Concatenates `NAME\\0` plus one `\\0`-terminated field per locale, sorted by name."""
    by_locale = {locale: dict(pairs) for locale, pairs in tables.items()}
    out = bytearray()
    for canonical in sorted({fn for pairs in tables.values() for fn, _ in pairs}):
        out += canonical.encode("utf-8") + b"\0"
        for locale in tables:
            out += by_locale[locale].get(canonical, "").encode("utf-8") + b"\0"
    return bytes(out)


def c_string_lines(data: bytes) -> list[str]:
    """Renders NUL-separated text as adjacent string literals with octal escapes."""
    lines: list[str] = []
    current = ""
    for chunk in data.split(b"\0")[:-1]:
        piece = "".join(chr(b) if 0x20 <= b < 0x7F and b not in (0x22, 0x5C) else f"\\{b:03o}" for b in chunk)
        piece += "\\000"
        if current and len(current) + len(piece) + 6 > LINE_WIDTH:
            lines.append(f'    "{current}"')
            current = ""
        current += piece
    if current:
        lines.append(f'    "{current}"')
    return lines


def render(names_by_locale: dict[str, dict[str, str | None]]) -> dict[Path, str]:
    tables = localized_tables(names_by_locale)
    data = records(tables)
    enumerators = dict(LOCALES)
    columns = list(tables)

    header = f"""\
// GENERATED by tools/locale/generate_function_names.py from tools/locale/data; do not edit.
// Excel function names whose spelling in a locale differs from English.

#ifndef FORMULON_EVAL_LOCALE_FUNCTION_NAMES_H_
#define FORMULON_EVAL_LOCALE_FUNCTION_NAMES_H_

#include <cstddef>

#include "excel_profile.h"

namespace formulon {{
namespace eval {{

/// Records sorted by canonical name: `NAME\\0` followed by one `\\0`-terminated
/// UTF-8 field per column; an empty field means the locale shows `NAME`.
extern const char kLocaleFunctionNames[];
extern const std::size_t kLocaleFunctionNamesSize;
inline constexpr int kLocaleFunctionNameColumns = {len(columns)};

/// Field of `locale` within a record, or -1 when every name is English.
int locale_function_name_column(ExcelLocale locale) noexcept;

}}  // namespace eval
}}  // namespace formulon

#endif  // FORMULON_EVAL_LOCALE_FUNCTION_NAMES_H_
"""

    literal = c_string_lines(data)
    counts = ", ".join(f"{locale} {len(tables[locale])}" for locale in columns)
    body: list[str] = [
        "// GENERATED by tools/locale/generate_function_names.py from tools/locale/data; do not edit.",
        f"// {len(data)} bytes; localized names: {counts}.",
        f"// @size-budget: {-(-len(data) // 1024)} KB",
        "",
        '#include "eval/locale_function_names.h"',
        "",
        "namespace formulon {",
        "namespace eval {",
        "",
        "const char kLocaleFunctionNames[] =",
        *literal[:-1],
        literal[-1] + ";",
        "const std::size_t kLocaleFunctionNamesSize = sizeof(kLocaleFunctionNames) - 1;",
        "",
        "int locale_function_name_column(ExcelLocale locale) noexcept {",
        "  switch (locale) {",
    ]
    for index, locale in enumerate(columns):
        body.append(f"    case ExcelLocale::{enumerators[locale]}:")
        body.append(f"      return {index};")
    body += [
        "    default:",
        "      return -1;",
        "  }",
        "}",
        "",
        "}  // namespace eval",
        "}  // namespace formulon",
        "",
    ]
    return {HEADER_PATH: header, SOURCE_PATH: "\n".join(body)}


def outputs() -> tuple[dict[Path, str], dict[str, list[str]]]:
    names_by_locale = {locale: load_names(locale) for locale, _ in LOCALES}
    return render(names_by_locale), catalog_gaps(names_by_locale)


def report_gaps(gaps: dict[str, list[str]]) -> None:
    total = sum(len(missing) for missing in gaps.values())
    print(f"catalog gap: {total}", file=sys.stderr)
    for locale, missing in gaps.items():
        print(f"  {locale}: {len(missing)}: {' '.join(missing)}", file=sys.stderr)


def check(paths: dict[Path, Path] | None = None) -> int:
    """Returns 0 when the tracked outputs match, 1 on drift, 2 on a catalog gap."""
    rendered, gaps = outputs()
    drift = 0
    for path, text in rendered.items():
        target = (paths or {}).get(path, path)
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            print(f"{target} is out of date. {REGENERATION_GUIDANCE}", file=sys.stderr)
            drift = 1
    if drift:
        return drift
    if gaps:
        report_gaps(gaps)
        return 2
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify the tracked outputs instead of writing")
    args = parser.parse_args()
    if args.check:
        return check()
    rendered, gaps = outputs()
    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8")
    if gaps:
        report_gaps(gaps)
        return 2
    print("catalog gap: 0", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
