#!/usr/bin/env python3
"""Binding-glue generator.

Reads tools/codegen/binding_manifest.yaml and emits the three binding
TUs (C ABI / embind / N-API) that surface each manifest entry. The
generator is purely textual: every entry maps to a fixed template per
body kind, and the C++ output is deliberately verbose so the diff
against the previous hand-written code is reviewable line-by-line.

Usage:
    python3 tools/codegen/gen_bindings.py
        [--manifest PATH]
        [--out-c-api DIR]
        [--out-embind DIR]
        [--out-node DIR]

By default the manifest and output directories are derived from the
repository root (one level up from this file).

The snapshot test (tests/codegen/binding_manifest_test.py) shells out to
this script in dry-run mode and compares the output to checked-in
snapshots, so any drift in the generator is reviewable.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Tuple

try:
    import yaml  # type: ignore
except ImportError as exc:  # pragma: no cover - install hint only.
    sys.stderr.write(
        "PyYAML is required. Install with `pip install pyyaml` or use the\n"
        "tools/oracle/.venv (`tools/oracle/.venv/bin/pip install pyyaml`).\n"
    )
    raise SystemExit(1) from exc


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_MANIFEST = REPO_ROOT / "tools" / "codegen" / "binding_manifest.yaml"
DEFAULT_OUT_CAPI = REPO_ROOT / "src" / "c_api" / "generated"
DEFAULT_OUT_EMBIND = REPO_ROOT / "src" / "wasm" / "generated"
DEFAULT_OUT_NODE = REPO_ROOT / "src" / "node_addon" / "generated"


# ---------------------------------------------------------------------------
# Manifest schema validation
# ---------------------------------------------------------------------------

VALID_BODY_KINDS = {
    "direct_size_t",
    "status_uint32_out",
    "status_sizet_out_with_sheet",
}

REQUIRED_FIELDS = (
    "name",
    "area",
    "body",
    "accessor",
    "js_method",
    "embind_cpp",
    "node_cpp",
)


def _load_manifest(path: Path) -> Tuple[int, List[dict]]:
    """Parse the YAML manifest and return (schema_version, entries)."""
    raw = yaml.safe_load(path.read_text())
    if not isinstance(raw, dict):
        raise SystemExit(f"{path}: manifest must be a mapping, got {type(raw).__name__}")
    version = raw.get("version", 1)
    funcs = raw.get("functions") or []
    if not isinstance(funcs, list):
        raise SystemExit(f"{path}: `functions` must be a list, got {type(funcs).__name__}")
    for i, entry in enumerate(funcs):
        if not isinstance(entry, dict):
            raise SystemExit(f"{path}: functions[{i}] must be a mapping")
        for field in REQUIRED_FIELDS:
            if field not in entry:
                raise SystemExit(f"{path}: functions[{i}] missing required field `{field}`")
        if entry["body"] not in VALID_BODY_KINDS:
            raise SystemExit(
                f"{path}: functions[{i}].body={entry['body']!r} not in {sorted(VALID_BODY_KINDS)}"
            )
    return int(version), funcs


# ---------------------------------------------------------------------------
# Shared header banner
# ---------------------------------------------------------------------------

_BANNER_LICENSE_APACHE = (
    "// Copyright 2026 libraz. Licensed under the Apache License, Version 2.0."
)
_BANNER_LICENSE_MIT = "// Copyright 2026 libraz. Licensed under the MIT License."

_GEN_BANNER = (
    "//\n"
    "// AUTO-GENERATED by tools/codegen/gen_bindings.py from\n"
    "// tools/codegen/binding_manifest.yaml. DO NOT EDIT BY HAND.\n"
    "// To change behaviour, edit the manifest and re-run the generator.\n"
)


def _file_header(license_banner: str, summary: str) -> str:
    return f"{license_banner}\n//\n// {summary}\n{_GEN_BANNER}\n"


# ---------------------------------------------------------------------------
# C ABI emitter
# ---------------------------------------------------------------------------
#
# Two patterns:
#
#   direct_size_t:
#       extern "C" size_t NAME(const fm_workbook_t* wb) {
#         if (wb == nullptr) {
#           return 0;
#         }
#         return ACCESSOR;
#       }
#
#   status_uint32_out:
#       extern "C" fm_status_t NAME(fm_workbook_t* wb, uint32_t* out_count) {
#         clear_last_error();
#         if (wb == nullptr || out_count == nullptr) {
#           return set_binding_error(
#               formulon::FormulonErrorCode::kBindingNullPointer,
#               "NAME: NULL argument");
#         }
#         *out_count = static_cast<uint32_t>(ACCESSOR);
#         return 0;
#       }
#
#   status_sizet_out_with_sheet:
#       extern "C" fm_status_t NAME(const fm_workbook_t* wb, size_t sheet_index,
#                                   size_t* out_count) {
#         clear_last_error();
#         if (wb == nullptr || out_count == nullptr) {
#           return set_binding_error(...kBindingNullPointer, "NAME: NULL argument");
#         }
#         if (sheet_index >= wb->workbook().sheet_count()) {
#           return set_binding_error(...kInvalidArgument,
#               "NAME: sheet_index out of range",
#               "sheet_index=" + std::to_string(sheet_index) + ...);
#         }
#         *out_count = ACCESSOR;
#         return 0;
#       }


_CAPI_BODY_DIRECT_SIZE_T = '''\
extern "C" size_t {name}(const fm_workbook_t* wb) {{
  if (wb == nullptr) {{
    return 0;
  }}
  return {accessor};
}}
'''

_CAPI_BODY_STATUS_U32_OUT = '''\
extern "C" fm_status_t {name}(fm_workbook_t* wb, uint32_t* out_count) {{
  clear_last_error();
  if (wb == nullptr || out_count == nullptr) {{
    return set_binding_error(formulon::FormulonErrorCode::kBindingNullPointer,
                             "{name}: NULL argument");
  }}
  *out_count = static_cast<uint32_t>({accessor});
  return 0;
}}
'''

_CAPI_BODY_STATUS_SIZE_WITH_SHEET = '''\
extern "C" fm_status_t {name}(const fm_workbook_t* wb, size_t sheet_index, size_t* out_count) {{
  clear_last_error();
  if (wb == nullptr || out_count == nullptr) {{
    return set_binding_error(formulon::FormulonErrorCode::kBindingNullPointer,
                             "{name}: NULL argument");
  }}
  if (sheet_index >= wb->workbook().sheet_count()) {{
    return set_binding_error(
        formulon::FormulonErrorCode::kInvalidArgument, "{name}: sheet_index out of range",
        "sheet_index=" + std::to_string(sheet_index) + " sheet_count=" + std::to_string(wb->workbook().sheet_count()));
  }}
  *out_count = {accessor};
  return 0;
}}
'''


def _emit_capi(entries: List[dict]) -> Dict[str, str]:
    """Emit one .cpp per `area` containing the C ABI bodies."""
    files: Dict[str, str] = {}
    by_area: Dict[str, List[dict]] = {}
    for e in entries:
        by_area.setdefault(e["area"], []).append(e)

    for area, items in sorted(by_area.items()):
        summary = (
            f"Generated C ABI bodies for the `{area}` group. The public\n"
            "// declarations live in src/c_api/formulon_c.h; this TU only\n"
            "// supplies the implementations the manifest can express."
        )
        header = _file_header(_BANNER_LICENSE_APACHE, summary)
        out = header
        out += "\n"
        out += "#include <cstddef>\n"
        out += "#include <cstdint>\n"
        out += "#include <string>\n"
        out += "\n"
        out += '#include "c_api/formulon_c.h"\n'
        out += '#include "c_api/parts/common.h"\n'
        out += '#include "io/styles_reader.h"\n'
        out += '#include "sheet.h"\n'
        out += '#include "utils/error.h"\n'
        out += '#include "workbook.h"\n'
        out += "\n"
        out += "using formulon::c_api::parts::clear_last_error;\n"
        out += "using formulon::c_api::parts::set_binding_error;\n"
        out += "\n"
        for e in sorted(items, key=lambda x: x["name"]):
            out += _emit_capi_entry(e)
            out += "\n"
        files[f"{area}.cpp"] = out
    return files


def _emit_capi_entry(e: dict) -> str:
    body = e["body"]
    if body == "direct_size_t":
        tmpl = _CAPI_BODY_DIRECT_SIZE_T
    elif body == "status_uint32_out":
        tmpl = _CAPI_BODY_STATUS_U32_OUT
    elif body == "status_sizet_out_with_sheet":
        tmpl = _CAPI_BODY_STATUS_SIZE_WITH_SHEET
    else:
        raise AssertionError(f"unknown body kind: {body}")
    return tmpl.format(name=e["name"], accessor=e["accessor"])


# ---------------------------------------------------------------------------
# embind emitter
# ---------------------------------------------------------------------------
#
# Each entry becomes a JsWorkbook::<methodName>() body that delegates to
# the corresponding C ABI function. Bodies follow the project's existing
# JsWorkbook pattern: NULL handle check first, then call the C ABI.

_EMBIND_BODY_DIRECT_SIZE_T = '''\
uint32_t JsWorkbook::{embind_cpp}() const {{
  if (handle_ == nullptr) {{
    return 0U;
  }}
  return static_cast<uint32_t>({capi}(handle_));
}}
'''

_EMBIND_BODY_STATUS_U32_OUT = '''\
uint32_t JsWorkbook::{embind_cpp}() const {{
  if (handle_ == nullptr) {{
    return 0U;
  }}
  uint32_t n = 0;
  if ({capi}(handle_, &n) != 0) {{
    return 0U;
  }}
  return n;
}}
'''

_EMBIND_BODY_STATUS_SIZE_WITH_SHEET = '''\
uint32_t JsWorkbook::{embind_cpp}(uint32_t sheet) const {{
  if (handle_ == nullptr) {{
    return 0U;
  }}
  std::size_t count = 0;
  if ({capi}(handle_, sheet, &count) != 0) {{
    return 0U;
  }}
  return static_cast<uint32_t>(count);
}}
'''


def _emit_embind(entries: List[dict]) -> Dict[str, str]:
    """Emit one .cpp per `area` containing JsWorkbook bodies."""
    files: Dict[str, str] = {}
    by_area: Dict[str, List[dict]] = {}
    for e in entries:
        by_area.setdefault(e["area"], []).append(e)

    for area, items in sorted(by_area.items()):
        summary = (
            f"Generated embind glue for the `{area}` group: JsWorkbook\n"
            "// method bodies that delegate to the C ABI passthroughs."
        )
        header = _file_header(_BANNER_LICENSE_APACHE, summary)
        out = header
        out += "\n"
        out += "#include <cstddef>\n"
        out += "#include <cstdint>\n"
        out += "\n"
        out += '#include "c_api/formulon_c.h"\n'
        out += '#include "wasm/parts/workbook.h"\n'
        out += "\n"
        out += "namespace formulon {\n"
        out += "namespace wasm {\n"
        out += "namespace parts {\n"
        out += "\n"
        for e in sorted(items, key=lambda x: x["embind_cpp"]):
            out += _emit_embind_entry(e)
            out += "\n"
        out += "}  // namespace parts\n"
        out += "}  // namespace wasm\n"
        out += "}  // namespace formulon\n"
        files[f"{area}.cpp"] = out
    return files


def _emit_embind_entry(e: dict) -> str:
    body = e["body"]
    if body == "direct_size_t":
        tmpl = _EMBIND_BODY_DIRECT_SIZE_T
    elif body == "status_uint32_out":
        tmpl = _EMBIND_BODY_STATUS_U32_OUT
    elif body == "status_sizet_out_with_sheet":
        tmpl = _EMBIND_BODY_STATUS_SIZE_WITH_SHEET
    else:
        raise AssertionError(f"unknown body kind: {body}")
    return tmpl.format(embind_cpp=e["embind_cpp"], capi=e["name"])


# ---------------------------------------------------------------------------
# N-API emitter
# ---------------------------------------------------------------------------
#
# N-API method bodies follow the addon's existing pattern:
#   - NULL handle returns Napi::Number(0).
#   - Direct passthroughs cast the size_t / uint32 result into a JS Number.

_NODE_BODY_DIRECT_SIZE_T = '''\
Napi::Value Workbook::{node_cpp}(const Napi::CallbackInfo& info) {{
  Napi::Env env = info.Env();
  if (handle_ == nullptr) {{
    return Napi::Number::New(env, 0);
  }}
  return Napi::Number::New(env, static_cast<double>({capi}(handle_)));
}}
'''

_NODE_BODY_STATUS_U32_OUT = '''\
Napi::Value Workbook::{node_cpp}(const Napi::CallbackInfo& info) {{
  Napi::Env env = info.Env();
  if (handle_ == nullptr) {{
    return Napi::Number::New(env, 0);
  }}
  uint32_t n = 0;
  if ({capi}(handle_, &n) != 0) {{
    return Napi::Number::New(env, 0);
  }}
  return Napi::Number::New(env, n);
}}
'''

_NODE_BODY_STATUS_SIZE_WITH_SHEET = '''\
Napi::Value Workbook::{node_cpp}(const Napi::CallbackInfo& info) {{
  Napi::Env env = info.Env();
  if (handle_ == nullptr) {{
    return Napi::Number::New(env, 0);
  }}
  const std::size_t sheet = static_cast<std::size_t>(ArgU32(info, 0));
  std::size_t count = 0;
  if ({capi}(handle_, sheet, &count) != 0) {{
    return Napi::Number::New(env, 0);
  }}
  return Napi::Number::New(env, static_cast<double>(count));
}}
'''


def _emit_node(entries: List[dict]) -> Dict[str, str]:
    """Emit one .cc per `area` containing Workbook N-API method bodies."""
    files: Dict[str, str] = {}
    by_area: Dict[str, List[dict]] = {}
    for e in entries:
        by_area.setdefault(e["area"], []).append(e)

    for area, items in sorted(by_area.items()):
        summary = (
            f"Generated N-API glue for the `{area}` group: Workbook\n"
            "// method bodies that delegate to the C ABI passthroughs."
        )
        header = _file_header(_BANNER_LICENSE_MIT, summary)
        out = header
        out += "\n"
        out += "#include <cstddef>\n"
        out += "#include <cstdint>\n"
        out += "\n"
        out += '#include "node_addon/parts/workbook_class.h"\n'
        out += "\n"
        out += "namespace formulon_node {\n"
        out += "\n"
        for e in sorted(items, key=lambda x: x["node_cpp"]):
            out += _emit_node_entry(e)
            out += "\n"
        out += "}  // namespace formulon_node\n"
        files[f"{area}.cc"] = out
    return files


def _emit_node_entry(e: dict) -> str:
    body = e["body"]
    if body == "direct_size_t":
        tmpl = _NODE_BODY_DIRECT_SIZE_T
    elif body == "status_uint32_out":
        tmpl = _NODE_BODY_STATUS_U32_OUT
    elif body == "status_sizet_out_with_sheet":
        tmpl = _NODE_BODY_STATUS_SIZE_WITH_SHEET
    else:
        raise AssertionError(f"unknown body kind: {body}")
    return tmpl.format(node_cpp=e["node_cpp"], capi=e["name"])


# ---------------------------------------------------------------------------
# File writer
# ---------------------------------------------------------------------------


def _clang_format(content: str, path: Path) -> str:
    """Pipe `content` through clang-format using `path`'s filename for style detection.

    Ensures generated files agree with the project-wide format-check (which
    runs `clang-format --dry-run --Werror` over `src/`). Falls back to the
    raw content if clang-format is unavailable, so a stripped CI image can
    still run the generator's --check mode against a previously-formatted
    snapshot.
    """
    cf = shutil.which("clang-format")
    if cf is None:
        return content
    proc = subprocess.run(
        [cf, f"--assume-filename={path.name}"],
        input=content,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        sys.stderr.write(
            f"clang-format failed on {path.name}: {proc.stderr}\n"
            "falling back to raw codegen output\n"
        )
        return content
    return proc.stdout


def _write_if_changed(path: Path, content: str) -> bool:
    """Write `content` to `path` only if it differs. Returns True on write."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == content:
        return False
    path.write_text(content)
    return True


def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate binding glue from the YAML manifest.")
    p.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    p.add_argument("--out-c-api", type=Path, default=DEFAULT_OUT_CAPI)
    p.add_argument("--out-embind", type=Path, default=DEFAULT_OUT_EMBIND)
    p.add_argument("--out-node", type=Path, default=DEFAULT_OUT_NODE)
    p.add_argument(
        "--check",
        action="store_true",
        help="Do not write files; exit non-zero if any output would change.",
    )
    args = p.parse_args(argv)

    version, entries = _load_manifest(args.manifest)
    if version != 1:
        sys.stderr.write(f"manifest schema version {version} is not supported (expected 1)\n")
        return 2

    capi_files = _emit_capi(entries)
    embind_files = _emit_embind(entries)
    node_files = _emit_node(entries)

    drift = False
    for name, content in sorted(capi_files.items()):
        target = args.out_c_api / name
        content = _clang_format(content, target)
        if args.check:
            if not target.exists() or target.read_text() != content:
                sys.stderr.write(f"drift: {target}\n")
                drift = True
        else:
            wrote = _write_if_changed(target, content)
            if wrote:
                sys.stdout.write(f"wrote {target}\n")
    for name, content in sorted(embind_files.items()):
        target = args.out_embind / name
        content = _clang_format(content, target)
        if args.check:
            if not target.exists() or target.read_text() != content:
                sys.stderr.write(f"drift: {target}\n")
                drift = True
        else:
            wrote = _write_if_changed(target, content)
            if wrote:
                sys.stdout.write(f"wrote {target}\n")
    for name, content in sorted(node_files.items()):
        target = args.out_node / name
        content = _clang_format(content, target)
        if args.check:
            if not target.exists() or target.read_text() != content:
                sys.stderr.write(f"drift: {target}\n")
                drift = True
        else:
            wrote = _write_if_changed(target, content)
            if wrote:
                sys.stdout.write(f"wrote {target}\n")

    if args.check and drift:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
