"""Python binding parity surface tests."""

from __future__ import annotations

import unittest

import formulon
from formulon import (
    Workbook,
)


class SurfaceParityTests(unittest.TestCase):
    """Every advertised method must exist on the Workbook class."""

    METHODS = [
        "move_sheet",
        "remove_sheet",
        "rename_sheet",
        "set_defined_name",
        "set_defined_name_scoped",
        "set_error",
        "insert_rows",
        "delete_rows",
        "insert_cols",
        "delete_cols",
        "calc_mode",
        "set_calc_mode",
        "pinned_now",
        "set_pinned_now",
        "clear_pinned_now",
        "excel_profile_id",
        "set_excel_profile_id",
        "partial_recalc",
        "lambda_text_at",
        "evaluate_formula_array",
        "add_merge",
        "remove_merge",
        "remove_merge_at",
        "clear_merges",
        "get_merges",
        "merge_count",
        "add_hyperlink",
        "remove_hyperlink",
        "remove_hyperlink_at",
        "clear_hyperlinks",
        "get_hyperlinks",
        "hyperlink_count",
        "get_comment",
        "set_comment",
        "validation_count",
        "get_validation_at",
        "get_validations",
        "add_validation",
        "remove_validation_at",
        "clear_validations",
        "get_sheet_protection",
        "set_sheet_protection",
        "get_sheet_view",
        "set_sheet_zoom",
        "set_sheet_freeze",
        "set_sheet_tab_hidden",
        "set_sheet_visibility",
        "set_sheet_show_grid_lines",
        "set_sheet_show_row_col_headers",
        "set_sheet_show_zeros",
        "set_sheet_right_to_left",
        "set_sheet_tab_selected",
        "set_sheet_view_mode",
        "get_sheet_columns",
        "set_column_width",
        "set_column_hidden",
        "set_column_outline",
        "get_sheet_row_overrides",
        "set_row_height",
        "set_row_hidden",
        "set_row_outline",
        "evaluate_cf_range",
        "cf_count",
        "get_conditional_format_at",
        "get_conditional_formats",
        "add_conditional_format",
        "remove_conditional_format_at",
        "clear_conditional_formats",
        "get_cell_xf_index",
        "set_cell_xf_index",
        "get_cell_xf",
        "get_font",
        "get_fill",
        "get_border",
        "get_num_fmt",
        "font_count",
        "fill_count",
        "border_count",
        "cell_xf_count",
        "cell_style_count",
        "cell_style_xf_count",
        "add_font",
        "add_fill",
        "add_border",
        "add_num_fmt",
        "add_cell_xf",
        "get_cell_style",
        "get_cell_style_xf",
        "pivot_count",
        "pivot_layout",
        "pivot_cache_count",
        "pivot_cache_id_at",
        "pivot_cache_create",
        "pivot_cache_remove",
        "pivot_cache_field_count",
        "pivot_cache_field_name",
        "pivot_cache_field_add",
        "pivot_cache_field_clear",
        "pivot_cache_record_add",
        "pivot_cache_record_set_number",
        "pivot_cache_record_set_text",
        "pivot_create",
        "pivot_remove",
        "pivot_set_name",
        "pivot_set_anchor",
        "pivot_set_grand_totals",
        "pivot_field_add",
        "pivot_field_add_item",
        "pivot_field_add_item_at",
        "pivot_field_set_axis",
        "pivot_data_field_add",
        "pivot_data_field_set",
        "pivot_filter_add",
        "pivot_set_row_field_order",
        "pivot_set_col_field_order",
        "precedents",
        "dependents",
        "spill_info",
        "function_count",
        "function_name_at",
        "function_metadata",
        "localize_function_name",
        "canonicalize_function_name",
        "external_link_count",
        "get_external_link_at",
        "get_external_links",
        "save",
        "save_as",
        "save_with_diagnostics",
        "read_diagnostics",
    ]

    def test_all_methods_present(self) -> None:
        for name in self.METHODS:
            self.assertTrue(hasattr(Workbook, name), f"Workbook missing method: {name}")

    def test_default_workbook_uses_english_profile(self) -> None:
        with Workbook.create_default() as wb:
            self.assertEqual(wb.excel_profile_id(), "win-365-en_US")

    def test_public_types_exported(self) -> None:
        for name in (
            "MergeRange",
            "Comment",
            "Hyperlink",
            "DataValidation",
            "DataValidationInput",
            "SheetProtection",
            "SheetView",
            "ConditionalFormat",
            "ConditionalFormatInput",
            "CfMatch",
            "CfCellResult",
            "CellNode",
            "SpillInfo",
            "FunctionMetadata",
            "CellXf",
            "ColorSpec",
            "FontRecord",
            "FillRecord",
            "CellStyle",
            "ExternalLink",
            "PivotCell",
            "PivotLayout",
            "PivotFieldSpec",
            "PivotDataFieldSpec",
            "PivotFilterSpec",
            "CalcMode",
            "PivotAxis",
            "PivotAggregation",
            "MergedFunctionMetadata",
            "merge_function_metadata",
        ):
            self.assertTrue(hasattr(formulon, name), f"formulon missing: {name}")


if __name__ == "__main__":
    unittest.main()
