// Copyright 2026 libraz. Licensed under the Apache License, Version 2.0.
//
// Writer for `xl/comments<N>.xml`. Emits the modern shape with an
// inline author table plus a flat `<commentList>` of `<comment>`
// elements (one per `CellComment`). Rich-text fidelity is intentionally
// dropped: each comment is emitted as a single `<r><t>...</t></r>` run.
//
// The writer also produces a minimal VML drawing stub for legacy Excel
// compatibility: the bytes describe a single transparent shape at the
// origin so Excel won't reject the package, and the actual per-comment
// bounding boxes are left to be regenerated by Excel on first save.
// VML round-trip from non-trivial sources is out of scope; the
// passthrough mechanism on the workbook handles preservation when the
// reader carries the original bytes through.
//
// Design references:
//   * backup/plans/04-xlsx-io.md §4.6 (Comment / VML round-trip)

#ifndef FORMULON_IO_COMMENTS_WRITER_H_
#define FORMULON_IO_COMMENTS_WRITER_H_

#include <string>
#include <vector>

#include "sheet.h"

namespace formulon::io {

/// Serialises a `CellComment` list into a complete `xl/comments<N>.xml`
/// document. The author table is built from the unique `author` strings
/// present in `comments` (in first-occurrence order); each `<comment>`
/// references its author by index. Empty `comments` returns the empty
/// string — the writer must NOT emit an empty comments part.
std::string write_comments(const std::vector<CellComment>& comments);

/// Produces a minimal VML drawing stub. Excel requires the part to
/// exist whenever a sheet has comments, but the bounding-box detail is
/// optional in modern viewers. We emit a single placeholder shape so
/// older renderers don't choke; layout is regenerated by Excel on the
/// first edit.
std::string write_vml_drawing_stub();

}  // namespace formulon::io

#endif  // FORMULON_IO_COMMENTS_WRITER_H_
