# Copyright 2026 libraz. Licensed under the Apache License, Version 2.0.
# Hand-rolled type stubs for the Formulon public surface.
# IDEs and type-checkers consume this rather than the runtime module.

from typing import Iterator, NamedTuple, Optional, Union

from ._c import ValueKind as ValueKind

__version__: str

class Value:
    kind: ValueKind
    number: Optional[float]
    boolean: Optional[bool]
    text: Optional[str]
    error_code: Optional[int]
    def to_python(self) -> Union[None, float, bool, str, "Value"]: ...

class Cell(NamedTuple):
    row: int
    col: int
    formula: Optional[str]
    value: Value

class DefinedName(NamedTuple):
    name: str
    formula: str

class Table(NamedTuple):
    name: str
    display_name: str
    ref: str
    sheet_index: int

class PassthroughPart(NamedTuple):
    path: str

class FormulonError(Exception):
    status: int
    status_name: str
    message: str
    context: str
    def __init__(self, status: int, *, op: str = ...) -> None: ...

class Workbook:
    def __init__(self) -> None: ...
    @classmethod
    def create_default(cls) -> "Workbook": ...
    @classmethod
    def create_empty(cls) -> "Workbook": ...
    @classmethod
    def load(cls, data: Union[bytes, bytearray, memoryview]) -> "Workbook": ...
    def __enter__(self) -> "Workbook": ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    def close(self) -> None: ...
    @property
    def is_valid(self) -> bool: ...
    def sheet_count(self) -> int: ...
    def sheet_name(self, index: int) -> str: ...
    def add_sheet(self, name: str) -> None: ...
    def set_number(self, sheet: int, row: int, col: int, value: float) -> None: ...
    def set_bool(self, sheet: int, row: int, col: int, value: bool) -> None: ...
    def set_text(self, sheet: int, row: int, col: int, value: str) -> None: ...
    def set_blank(self, sheet: int, row: int, col: int) -> None: ...
    def set_formula(self, sheet: int, row: int, col: int, formula: str) -> None: ...
    def get_value(self, sheet: int, row: int, col: int) -> Value: ...
    def recalc(self) -> None: ...
    def set_iterative(
        self, enabled: bool, max_iterations: int, max_change: float
    ) -> None: ...
    def save(self) -> bytes: ...
    def iter_cells(self, sheet: int) -> Iterator[Cell]: ...
    def iter_defined_names(self) -> Iterator[DefinedName]: ...
    def iter_tables(self) -> Iterator[Table]: ...
    def iter_passthrough(self) -> Iterator[PassthroughPart]: ...

def library_version() -> str: ...
def version_string() -> str: ...
def eval_formula(formula: str) -> Value: ...
